// Fichier de 160 questions d'entraînement monétique PayQuest
// Couvre les 5 grands piliers de l'ingénierie et de l'astreinte monétique bancaire.

class QuizQuestion {
  final String id;
  final String category;
  final String question;
  final List<String> options;
  final int correctIndex;
  final String explanation;
  final int xpReward;

  const QuizQuestion({
    required this.id,
    required this.category,
    required this.question,
    required this.options,
    required this.correctIndex,
    required this.explanation,
    this.xpReward = 30,
  });
}

class QuizQuestionsCatalog {
  static const List<QuizQuestion> allQuestions = [
    QuizQuestion(
      id: 'Q-001',
      category: 'ISO 8583 & MTI',
      question: 'Quel est le MTI standard d\'une demande d\'autorisation financière initiée par un terminal ?',
      options: ['0100', '0200', '0420', '0800'],
      correctIndex: 1,
      explanation: 'Le MTI 0200 correspond à une requête financière (Financial Transaction Request) avec engagement de débit immédiat.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-002',
      category: 'ISO 8583 & MTI',
      question: 'À quoi sert le message ISO 8583 avec MTI 0420 ?',
      options: ['Demande de solde de compte', 'Avis d\'extourne ou d\'annulation (Reversal Advice)', 'Test d\'écho de liaison télécom', 'Télécollecte de fin de journée'],
      correctIndex: 1,
      explanation: 'Le MTI 0420 est un Reversal Advice permettant d\'annuler une transaction lorsque le cash n\'a pas été distribué ou en cas de timeout.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-003',
      category: 'ISO 8583 & MTI',
      question: 'Quel Data Element (DE) contient le numéro d\'audit unique de transaction STAN ?',
      options: ['DE 3', 'DE 4', 'DE 11', 'DE 37'],
      correctIndex: 2,
      explanation: 'Le DE 11 est le Systems Trace Audit Number (STAN), un identifiant séquentiel à 6 chiffres généré par l\'initiateur.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-004',
      category: 'ISO 8583 & MTI',
      question: 'Dans le bitmap ISO 8583, comment est signalée la présence des champs secondaires (DE 65 à 128) ?',
      options: ['Par le bit 64 activé', 'Par le bit 1 du bitmap primaire mis à 1', 'Par la présence du DE 39', 'Par un MTI étendu à 5 chiffres'],
      correctIndex: 1,
      explanation: 'Le premier bit du bitmap primaire (Bit 1) indique la présence du bitmap secondaire lorsqu\'il est égal à 1.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-005',
      category: 'ISO 8583 & MTI',
      question: 'Quelle est la fonction du MTI 0800 en ISO 8583 ?',
      options: ['Autorisation de retrait GAB', 'Échange réseau / Network Management Request (Logon, Echo test, Key exchange)', 'Demande de compensation nocturne', 'Règlement brut en temps réel (RTGS)'],
      correctIndex: 1,
      explanation: 'Le MTI 0800 gère l\'administration réseau (Network Management) : ouverture de session (Logon), coupure (Logoff), test d\'écho et échange de clés.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-006',
      category: 'ISO 8583 & MTI',
      question: 'Quel Data Element ISO 8583 transporte le Processing Code composé de 6 chiffres ?',
      options: ['DE 2', 'DE 3', 'DE 4', 'DE 22'],
      correctIndex: 1,
      explanation: 'Le DE 3 (Processing Code) est composé de 6 chiffres : Type d\'opération (2 ch.), Compte source (2 ch.), Compte cible (2 ch.).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-007',
      category: 'ISO 8583 & MTI',
      question: 'Si le DE 3 (Processing Code) vaut \'010000\', de quelle transaction s\'agit-il ?',
      options: ['Retrait d\'espèces sur compte courant', 'Paiement de biens ou services sur compte courant', 'Virement de compte à compte', 'Demande de solde'],
      correctIndex: 0,
      explanation: 'Le code \'01\' en préfixe du Processing Code représente un retrait d\'espèces (Cash Withdrawal). \'00\' désigne le compte courant/chèque.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-008',
      category: 'ISO 8583 & MTI',
      question: 'Quel champ ISO 8583 transporte le montant de la transaction exprimé avec 2 décimales implicites ?',
      options: ['DE 3', 'DE 4', 'DE 5', 'DE 49'],
      correctIndex: 1,
      explanation: 'Le DE 4 (Amount, Transaction) transporte le montant sur 12 chiffres numériques (ex: 000000010000 pour 100,00).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-009',
      category: 'ISO 8583 & MTI',
      question: 'Quel DE transporte le Retrieval Reference Number (RRN) sur 12 caractères alphanumériques ?',
      options: ['DE 11', 'DE 12', 'DE 37', 'DE 41'],
      correctIndex: 2,
      explanation: 'Le DE 37 (RRN - Retrieval Reference Number) est le numéro de référence unique de dossier de transaction souvent dérivé du STAN et de l\'heure.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-010',
      category: 'ISO 8583 & MTI',
      question: 'Quelle est la différence fondamentale entre un MTI 0100 et un MTI 0200 ?',
      options: ['Le 0100 est une demande d\'autorisation (réservation de solde), le 0200 est une transaction financière directe (débit ferme)', 'Le 0100 est pour Mastercard, le 0200 pour Visa', 'Le 0100 est réservé aux paiements sans contact', 'Le 0200 n\'a pas besoin de code PIN'],
      correctIndex: 0,
      explanation: 'Le MTI 0100 effectue une réservation (pré-autorisation) sans impacter immédiatement les écritures comptables, alors que le 0200 débouche sur un débit comptable immédiat.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-011',
      category: 'ISO 8583 & MTI',
      question: 'Quel DE spécifie le Card Acceptor Terminal ID (TID) à 8 caractères ?',
      options: ['DE 41', 'DE 42', 'DE 43', 'DE 32'],
      correctIndex: 0,
      explanation: 'Le DE 41 identifie le terminal physique (TID - Terminal Identification). Le DE 42 identifie le commerçant (MID).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-012',
      category: 'ISO 8583 & MTI',
      question: 'Quel DE contient le Card Acceptor Identification Code (Merchant ID / MID) ?',
      options: ['DE 41', 'DE 42', 'DE 48', 'DE 102'],
      correctIndex: 1,
      explanation: 'Le DE 42 est le Merchant ID (MID) à 15 caractères identifiant l\'entité commerçante ou le point de vente acquéreur.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-013',
      category: 'ISO 8583 & MTI',
      question: 'Quel est le rôle du DE 49 dans un message financier ISO 8583 ?',
      options: ['Code postal du porteur', 'Code devise de la transaction selon ISO 4217 (ex: 978 pour EUR, 952 pour XOF)', 'Code pays du commerçant', 'Taux de change interbancaire'],
      correctIndex: 1,
      explanation: 'Le DE 49 est le code devise numérique à 3 chiffres selon la norme ISO 4217 (ex: 978 pour l\'Euro, 840 pour l\'USD, 952 pour le Franc CFA).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-014',
      category: 'ISO 8583 & MTI',
      question: 'Que contient le DE 22 (Point of Service Entry Mode Code) ?',
      options: ['Le type de matériel utilisé par le commerçant', 'Le mode de lecture de la carte (Piste magnétique, Puce contact, Sans contact NFC, Fallback, Saisie manuelle)', 'L\'adresse IP du serveur d\'autorisation', 'Le niveau de batterie du terminal'],
      correctIndex: 1,
      explanation: 'Le DE 22 renseigne sur la méthode de saisie des données de carte (POS Entry Mode : 02=Piste, 05=Puce ICC, 07=Contactless, 80=Fallback).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-015',
      category: 'ISO 8583 & MTI',
      question: 'Dans le DE 22, que signifie la valeur \'051\' ou \'05\' pour les deux premiers chiffres ?',
      options: ['Transaction saisie manuellement (VAD)', 'Lecture réussie de la puce EMV (Integrated Circuit Card)', 'Transaction piste dégradée (Fallback)', 'Paiement par QR Code'],
      correctIndex: 1,
      explanation: 'Le code \'05\' indique que les données proviennent de la lecture sécurisée de la puce EMV.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-016',
      category: 'ISO 8583 & MTI',
      question: 'Quel MTI représente la réponse d\'un émetteur à un message de Reversal 0420 ?',
      options: ['0410', '0430', '0421', '0210'],
      correctIndex: 1,
      explanation: 'La réponse à un avis d\'extourne (0420) est le MTI 0430 (Reversal Advice Response).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-017',
      category: 'ISO 8583 & MTI',
      question: 'Dans quelle version de la norme ISO 8583 le MTI commence-t-il par le chiffre \'1\' au lieu de \'0\' (ex: 1100, 1200) ?',
      options: ['Version 1987', 'Version 1993', 'Version 2003', 'Version ISO 20022'],
      correctIndex: 1,
      explanation: 'Le premier chiffre du MTI indique la version de la norme : 0 pour ISO 8583:1987, 1 pour ISO 8583:1993, 2 pour ISO 8583:2003.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-018',
      category: 'ISO 8583 & MTI',
      question: 'Quel DE contient le code d\'authentification du message (MAC) calculé sur l\'ensemble du message ISO 8583 ?',
      options: ['DE 52', 'DE 53', 'DE 64 ou DE 128', 'DE 90'],
      correctIndex: 2,
      explanation: 'Le DE 64 (fin du bitmap primaire) ou DE 128 (fin du bitmap secondaire) transporte le Message Authentication Code (MAC) garantissant l\'intégrité.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-019',
      category: 'ISO 8583 & MTI',
      question: 'Quel DE contient les données originales de la transaction lors d\'un Reversal 0420 (Original Data Elements) ?',
      options: ['DE 55', 'DE 90', 'DE 100', 'DE 104'],
      correctIndex: 1,
      explanation: 'Le DE 90 (Original Data Elements) contient l\'empreinte originale : MTI d\'origine, STAN d\'origine, date/heure d\'origine et code acquéreur.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-020',
      category: 'ISO 8583 & MTI',
      question: 'Quel est le rôle du DE 52 dans une transaction avec saisie de code secret ?',
      options: ['Transport du PIN Block chiffré', 'Date de naissance du client', 'Code de déverrouillage PUK', 'Numéro de téléphone du porteur'],
      correctIndex: 0,
      explanation: 'Le DE 52 (Personal Identification Number Data) transporte le PIN Block chiffré sous la clé TPK/ZPK.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-021',
      category: 'ISO 8583 & MTI',
      question: 'Quel format de longueur possède le DE 55 (EMV Data) dans la plupart des implémentations ISO 8583 ?',
      options: ['Fixe sur 255 caractères', 'Variable LLLVAR (3 chiffres de longueur suivis des données)', 'Variable LLVAR (2 chiffres de longueur)', 'Binaire 8 octets fixe'],
      correctIndex: 1,
      explanation: 'Le DE 55 est de type LLLVAR (Longueur sur 3 chiffres ex: 180 suivi des 180 octets ou caractères hexadécimaux des tags EMV).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-022',
      category: 'ISO 8583 & MTI',
      question: 'Que contient le DE 38 dans une réponse d\'autorisation positive 0110 ou 0210 ?',
      options: ['Le code d\'approbation d\'autorisation (Approval Code / Authorization ID Response)', 'Le solde restant du compte', 'Le taux d\'agios', 'Le numéro de série du serveur émetteur'],
      correctIndex: 0,
      explanation: 'Le DE 38 (Authorization Identification Response) est le code d\'autorisation à 6 caractères généré par l\'émetteur attestant de l\'accord.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-023',
      category: 'ISO 8583 & MTI',
      question: 'Quel est le rôle du DE 18 (Merchant Category Code - MCC) ?',
      options: ['Identifier le type d\'activité commerciale du commerçant (ex: 5411 pour supermarchés, 6011 pour GAB)', 'Indiquer le code fiscal du commerçant', 'Donner le code de zone géographique', 'Identifier le modèle de terminal'],
      correctIndex: 0,
      explanation: 'Le DE 18 est le MCC (Merchant Category Code) standardisé selon l\'ISO 18245 qui catégorifie l\'activité marchande pour la tarification et la conformité.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-024',
      category: 'ISO 8583 & MTI',
      question: 'Quel DE transporte le Track 2 Equivalent Data lorsque la carte est lue par piste ou par puce ?',
      options: ['DE 2', 'DE 14', 'DE 35', 'DE 45'],
      correctIndex: 2,
      explanation: 'Le DE 35 transporte les données de la piste 2 (PAN, date d\'expiration, code service, CVV/CVC, données discrétionnaires).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-025',
      category: 'ISO 8583 & MTI',
      question: 'Que contient le champ DE 102 dans une transaction de virement bancaire ou de paiement de facture ?',
      options: ['Numéro de compte source (Account Identification 1)', 'Nom du tiers bénéficiaire', 'Numéro de chèque', 'Code guichet'],
      correctIndex: 0,
      explanation: 'Le DE 102 identifie le compte source débité, tandis que le DE 103 identifie le compte de destination (Account Identification 2).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-026',
      category: 'ISO 8583 & MTI',
      question: 'Quel MTI est utilisé pour effectuer un échange de clés cryptographiques de session entre deux nœuds du switch ?',
      options: ['0800 avec Processing Code de gestion de clés (ex: 920000)', '0200 avec montant 0', '0100 avec PAN vide', '0500 Réconciliation'],
      correctIndex: 0,
      explanation: 'L\'échange de clés dynamiques s\'effectue via un MTI 0800 (Network Management) avec un code spécifique d\'échange de clés (Key Exchange).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-027',
      category: 'ISO 8583 & MTI',
      question: 'Dans une trame ISO 8583, comment sont encodés les champs dits \'LLVAR\' ?',
      options: ['Les données sont précédées de 2 chiffres indiquant leur longueur exacte', 'Les données ont toujours une longueur fixe de 2 octets', 'Les données se terminent par deux octets 0x00', 'Ce sont des champs réservés aux cartes de fidélité'],
      correctIndex: 0,
      explanation: 'LLVAR signifie \'Variable Length\' où les 2 premiers octets numériques spécifient la longueur des données qui suivent (ex: 16 pour 16 caractères).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-028',
      category: 'ISO 8583 & MTI',
      question: 'Que représente le DE 7 (Transmission Date and Time) ?',
      options: ['L\'heure d\'impression du ticket client', 'La date et l\'heure UTC de transmission au format MMDDhhmmss', 'La date de valeur comptable', 'L\'heure d\'expiration de la carte'],
      correctIndex: 1,
      explanation: 'Le DE 7 est l\'horodatage universel UTC à 10 chiffres (MMDDhhmmss) généré au moment de l\'émission du message sur le réseau.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-029',
      category: 'ISO 8583 & MTI',
      question: 'Quel MTI correspond à un message de confirmation de remise de lot (Settlement / Batch Upload) ?',
      options: ['0320', '0500', '0620', '0220'],
      correctIndex: 1,
      explanation: 'Le MTI 0500 (ou 0520) correspond aux messages de réconciliation, totalisation et clôture financière de lot (Settlement).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-030',
      category: 'ISO 8583 & MTI',
      question: 'Quel DE transporte le code pays acquéreur (Acquiring Institution Country Code) ?',
      options: ['DE 19', 'DE 20', 'DE 32', 'DE 49'],
      correctIndex: 0,
      explanation: 'Le DE 19 identifie le pays de l\'acquéreur selon la norme ISO 3166 à 3 chiffres numériques (ex: 250 pour la France, 840 pour les USA).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-031',
      category: 'ISO 8583 & MTI',
      question: 'Quel rôle joue le DE 32 (Acquiring Institution Identification Code) ?',
      options: ['Il contient le BIN (Bank Identification Number) ou l\'identifiant de la banque acquéreuse', 'Il contient l\'adresse MAC du switch', 'Il contient le numéro de compte du commerçant', 'Il contient le code postal du terminal'],
      correctIndex: 0,
      explanation: 'Le DE 32 identifie l\'institution financière qui a acquis la transaction (institution de capture).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-032',
      category: 'ISO 8583 & MTI',
      question: 'À quel événement opérationnel correspond l\'envoi d\'un message 0420 Reversal par un GAB ?',
      options: ['Le porteur a refusé le ticket de reçu', 'Le distributeur mécanique de billets s\'est bloqué après accord d\'autorisation (Incident Bourrage/Dispense Failure)', 'Le client a composé son code PIN trop vite', 'La caméra du GAB est tombée en panne'],
      correctIndex: 1,
      explanation: 'Si les billets ne sont pas physiquement délivrés au porteur (bourrage, capteur de dispense défaillant), le GAB émet immédiatement un 0420 pour annuler le débit.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-033',
      category: 'ISO 8583 & MTI',
      question: 'Dans le bitmap ISO, quelle est la taille en bits du bitmap primaire ?',
      options: ['32 bits', '64 bits', '128 bits', '256 bits'],
      correctIndex: 1,
      explanation: 'Le bitmap primaire est constitué de 64 bits (8 octets binaires ou 16 caractères hexadécimaux), correspondant aux DE 1 à 64.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-034',
      category: 'ISO 8583 & MTI',
      question: 'Quel DE est systématiquement utilisé pour véhiculer des données privées ou additionnelles définies par chaque réseau (National Private Use) ?',
      options: ['DE 48 et DE 63', 'DE 3', 'DE 11', 'DE 4'],
      correctIndex: 0,
      explanation: 'Les DE 48, DE 60, DE 62 et DE 63 sont traditionnellement réservés pour les formats de données privées spécifiques aux réseaux nationaux ou acquéreurs.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-035',
      category: 'ISO 8583 & MTI',
      question: 'Que signifie le MTI 0110 ?',
      options: ['Demande d\'autorisation émise par un TPE', 'Réponse à une demande d\'autorisation émise par l\'émetteur vers l\'acquéreur', 'Avis de débit direct', 'Notification de litige chargeback'],
      correctIndex: 1,
      explanation: 'Le MTI 0110 est la réponse d\'autorisation (Authorization Response) envoyée par le centre d\'autorisation vers le terminal via le switch.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-036',
      category: 'Codes DE39',
      question: 'Que signifie formellement le code de rejet DE39 = \'51\' ?',
      options: ['Carte expirée', 'Fonds insuffisants / Dépassement de découvert autorisé', 'Émetteur inaccessible / Timeout', 'PIN erroné'],
      correctIndex: 1,
      explanation: 'DE39=51 (Insufficient funds) est retourné par l\'émetteur lorsque le solde disponible ou le plafond est insuffisant.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-037',
      category: 'Codes DE39',
      question: 'Quel code DE39 est retourné en cas de timeout de réponse de l\'Émetteur ou coupure switch ?',
      options: ['00', '05', '55', '91'],
      correctIndex: 3,
      explanation: 'DE39=91 (Issuer or Switch inoperative) signale l\'expiration du délai d\'attente ou l\'indisponibilité du centre d\'autorisation émetteur.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-038',
      category: 'Codes DE39',
      question: 'Lorsqu\'un porteur saisit un code PIN erroné, quel code DE39 standard est renvoyé ?',
      options: ['51', '55', '68', '96'],
      correctIndex: 1,
      explanation: 'DE39=55 (Incorrect PIN) indique une non-concordance du PIN calculé sous HSM ou par la puce.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-039',
      category: 'Codes DE39',
      question: 'Que signifie le code de succès universel DE39 = \'00\' ?',
      options: ['Transaction annulée avec succès', 'Transaction approuvée / Complétée avec succès', 'En attente de compensation manuelle', 'PIN validé mais compte sous séquestre'],
      correctIndex: 1,
      explanation: 'DE39=00 (Approved or completed successfully) confirme l\'autorisation positive de la transaction.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-040',
      category: 'Codes DE39',
      question: 'Quelle est la signification du code DE39 = \'05\' (Do Not Honor) ?',
      options: ['Problème matériel sur le TPE', 'Refus générique de l\'émetteur sans précision de motif pour des raisons de discrétion bancaire', 'Carte périmée', 'Devise invalide'],
      correctIndex: 1,
      explanation: 'DE39=05 (Do Not Honor) est le refus générique le plus fréquent, émis quand la banque émettrice refuse le paiement sans en divulguer la raison exacte.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-041',
      category: 'Codes DE39',
      question: 'Quel code DE39 signale qu\'une carte bancaire a dépassé sa date de fin de validité ?',
      options: ['14', '33', '54', '57'],
      correctIndex: 2,
      explanation: 'DE39=54 (Expired card) indique que la date d\'expiration de la carte (DE 14) est antérieure à la date courante de la transaction.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-042',
      category: 'Codes DE39',
      question: 'Que signale le code DE39 = \'14\' (Invalid Card Number) ?',
      options: ['Le code PIN est bloqué', 'Le numéro de carte (PAN) est non attribué ou ne respecte pas l\'algorithme de Luhn', 'La carte est déclarée volée', 'Le terminal n\'est pas configuré'],
      correctIndex: 1,
      explanation: 'DE39=14 indique un PAN inexistant dans le référentiel de l\'émetteur ou invalide au contrôle de clé de Luhn (Mod 10).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-043',
      category: 'Codes DE39',
      question: 'Quelle action opérationnelle impose le code DE39 = \'41\' (Lost Card - Capture) sur un terminal ?',
      options: ['Retenter la transaction en mode piste', 'Confisquer ou retenir la carte physique (Capture card)', 'Demander une pièce d\'identité et valider en manuel', 'Changer de devise'],
      correctIndex: 1,
      explanation: 'DE39=41 (Lost card) est un code de capture indiquant une carte déclarée perdue ; le terminal (notamment GAB) doit avaler la carte.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-044',
      category: 'Codes DE39',
      question: 'Quel code DE39 signale une carte déclarée volée imposant également la capture physique ?',
      options: ['43', '51', '62', '75'],
      correctIndex: 0,
      explanation: 'DE39=43 (Stolen card, pick up) ordonne la capture de la carte suite à une déclaration formelle de vol par le porteur.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-045',
      category: 'Codes DE39',
      question: 'Que signifie le code DE39 = \'75\' (Allowable number of PIN tries exceeded) ?',
      options: ['Le terminal a planté pendant la saisie du PIN', 'Le compteur d\'essais PIN de la carte ou du système hôte a atteint son seuil maximal (généralement 3 essais)', 'Le code PIN a expiré après un an', 'Le code PIN comporte trop de chiffres'],
      correctIndex: 1,
      explanation: 'DE39=75 indique que le porteur a composé trop de codes PIN erronés consécutifs, provoquant le blocage de l\'application de paiement.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-046',
      category: 'Codes DE39',
      question: 'Que signifie le code DE39 = \'61\' (Exceeds withdrawal amount limit) ?',
      options: ['Le distributeur n\'a plus de billets', 'Le montant demandé dépasse le plafond de retrait autorisé pour cette carte sur la période', 'Le compte est clôturé', 'Le switch est en surchauffe'],
      correctIndex: 1,
      explanation: 'DE39=61 signale un dépassement de plafond périodique (journalier ou hebdomadaire) configuré pour le porteur.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-047',
      category: 'Codes DE39',
      question: 'Que signifie le code DE39 = \'62\' (Restricted card) ?',
      options: ['Carte limitée géographiquement, sectoriellement ou carte bloquée temporairement par la banque', 'Carte de crédit sans puce', 'Carte dont le plafond est nul', 'Carte prépayée anonyme'],
      correctIndex: 0,
      explanation: 'DE39=62 indique une restriction d\'usage (ex: blocage des paiements à l\'international, restriction e-commerce, ou mise en réserve administrative).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-048',
      category: 'Codes DE39',
      question: 'Quelle est la signification du code DE39 = \'63\' (Security Violation) ?',
      options: ['Le porteur a fui le magasin', 'Échec d\'authentification cryptographique (MAC invalide, ARQC non validé par le HSM, ou paquet corrompu)', 'Attaque par déni de service réseau', 'Carte démagnétisée'],
      correctIndex: 1,
      explanation: 'DE39=63 indique une violation des contrôles cryptographiques stricts (clé déphasée, MAC erroné, échec de vérification du cryptogramme ARQC).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-049',
      category: 'Codes DE39',
      question: 'Que signifie le code DE39 = \'68\' (Response received too late) ?',
      options: ['La réponse de l\'émetteur est arrivée après l\'expiration du timer d\'attente du switch ou de l\'acquéreur', 'Le porteur a mis plus de 2 minutes à taper son PIN', 'La transaction date d\'hier', 'La session réseau est coupée depuis 24h'],
      correctIndex: 0,
      explanation: 'DE39=68 est retourné lorsqu\'un nœud intermédiaire reçoit l\'autorisation de l\'émetteur trop tard, après avoir déjà abandonné ou envoyé un timeout au terminal.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-050',
      category: 'Codes DE39',
      question: 'Quel code DE39 indique une transaction en doublon (Duplicate Transaction) ?',
      options: ['94', '13', '82', '96'],
      correctIndex: 0,
      explanation: 'DE39=94 (Duplicate transmission) est généré lorsque le switch détecte une transaction avec un STAN et un RRN identiques déjà traitée récemment.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-051',
      category: 'Codes DE39',
      question: 'Que signifie le code DE39 = \'96\' (System Malfunction) ?',
      options: ['Le client n\'a pas de compte bancaire', 'Erreur interne logicielle ou anomalie non récupérable sur le serveur d\'autorisation', 'Le terminal n\'a plus de papier d\'impression', 'La carte est pliée'],
      correctIndex: 1,
      explanation: 'DE39=96 (System malfunction / Internal error) est levé par l\'hôte en cas d\'exception non gérée, crash de base de données ou panne composant interne.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-052',
      category: 'Codes DE39',
      question: 'Quel code DE39 est renvoyé lorsque le type de transaction n\'est pas autorisé pour ce porteur (ex: retrait avec carte de crédit sans avance de fonds) ?',
      options: ['57', '05', '12', '58'],
      correctIndex: 0,
      explanation: 'DE39=57 (Transaction not permitted to cardholder) indique que le contrat porteur n\'autorise pas cette opération spécifique.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-053',
      category: 'Codes DE39',
      question: 'Que signifie le code DE39 = \'58\' (Transaction not permitted to terminal) ?',
      options: ['Le terminal est trop ancien pour accepter EMV', 'L\'acquéreur ou le contrat commerçant n\'autorise pas ce type d\'opération sur ce terminal précis', 'Le commerçant n\'a pas payé son abonnement télécom', 'Le terminal est en cours de redémarrage'],
      correctIndex: 1,
      explanation: 'DE39=58 indique que le profil du terminal (TID) chez l\'acquéreur interdit cette typologie de flux (ex: remboursement non activé).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-054',
      category: 'Codes DE39',
      question: 'Que signifie le code DE39 = \'30\' (Format Error) ?',
      options: ['La carte bancaire est au format non standard', 'La syntaxe ou la structure des champs du message ISO 8583 est non conforme aux spécifications', 'Le montant n\'a pas le bon symbole monétaire', 'Le nom du porteur contient des accents non acceptés'],
      correctIndex: 1,
      explanation: 'DE39=30 (Format error) signale un champ mal formé, une longueur incorrecte d\'un élément LLVAR/LLLVAR ou un bitmap incohérent.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-055',
      category: 'Codes DE39',
      question: 'Dans quel cas précis un switch émet-il un code DE39 = \'92\' (Unable to route transaction) ?',
      options: ['Le routeur réseau du commerçant est éteint', 'Le BIN de la carte ne correspond à aucune table de routage active ou le lien d\'interconnexion réseau est down', 'Le client a changé de banque la veille', 'Le terminal n\'a pas d\'adresse IP valide'],
      correctIndex: 1,
      explanation: 'DE39=92 (Unable to route) intervient quand le switch ne trouve aucune route d\'acheminement pour le préfixe de carte (BIN) ou que la passerelle d\'échange est fermée.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-056',
      category: 'Codes DE39',
      question: 'Quelle est la différence fondamentale entre les codes de refus DE39=51 et DE39=61 ?',
      options: ['51 concerne le solde du compte ou le découvert ; 61 concerne les limites de plafond contractuel périodique de retrait/dépense', '51 est pour les cartes Visa, 61 pour Mastercard', '51 est un code de capture, 61 un code de rejet simple', '51 est levé par le commerçant, 61 par la banque'],
      correctIndex: 0,
      explanation: 'DE39=51 sanctionne l\'absence de provision sur le compte bancaire, tandis que DE39=61 sanctionne le dépassement du plafond d\'utilisation défini sur la carte indépendamment du solde.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-057',
      category: 'Codes DE39',
      question: 'Que signifie le code DE39 = \'12\' (Invalid Transaction) ?',
      options: ['Le montant est négatif ou la combinaison Processing Code / Type de compte n\'a pas de sens', 'La carte a été créée illégalement', 'Le terminal est volé', 'La transaction a eu lieu un dimanche'],
      correctIndex: 0,
      explanation: 'DE39=12 indique une transaction invalide dans sa sémantique métier (combinaison de paramètres incohérente, ex: demande de virement vers le même compte).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-058',
      category: 'Codes DE39',
      question: 'Que signifie le code DE39 = \'13\' (Invalid Amount) ?',
      options: ['Le montant est exprimé dans une devise inconnue', 'Le montant demandé est nul, supérieur au maximum absolu autorisé par le système ou incompatible avec les coupures du GAB', 'Le commerçant a accordé une remise non autorisée', 'Le montant a été arrondi au centime supérieur'],
      correctIndex: 1,
      explanation: 'DE39=13 est émis lorsque le montant est non traitable (ex: retrait GAB de 12 euros impossible avec des billets de 10 et 20, ou montant = 0).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-059',
      category: 'Codes DE39',
      question: 'Lorsqu\'un terminal reçoit le code DE39 = \'01\' (Refer to card issuer), que doit faire l\'opérateur de caisse ?',
      options: ['Annuler la vente et confisquer la carte', 'Inviter le porteur à contacter sa banque ou faire un appel centre d\'autorisation vocal', 'Refaire immédiatement la même opération sans poser de question', 'Redémarrer le TPE'],
      correctIndex: 1,
      explanation: 'DE39=01 est une demande d\'appel au centre d\'autorisation (Voice Referral) pour contrôle d\'identité ou validation téléphonique manuelle.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-060',
      category: 'Codes DE39',
      question: 'Que signifie le code DE39 = \'03\' (Invalid Merchant) ?',
      options: ['Le commerçant a fermé son magasin', 'Le MID (Merchant ID) n\'est pas reconnu ou est désactivé sur le serveur acquéreur', 'Le commerçant ne vend pas les bons produits', 'Le nom du commerce contient une faute d\'orthographe'],
      correctIndex: 1,
      explanation: 'DE39=03 indique que le numéro commerçant (DE 42) n\'est pas actif ou n\'existe pas dans le référentiel de l\'acquéreur.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-061',
      category: 'Codes DE39',
      question: 'Quel code DE39 signale un échec de vérification du code cryptographique CVV2 / CVC2 lors d\'une vente en ligne (e-commerce) ?',
      options: ['44 ou N7', '51', '00', '91'],
      correctIndex: 0,
      explanation: 'Le code de rejet CVV2/CVC2 incorrect est souvent traduit par le code DE39=44 ou N7 selon les spécifications des schémas de cartes.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-062',
      category: 'Codes DE39',
      question: 'Que signifie le code DE39 = \'76\' ou \'78\' dans certains réseaux de switch ?',
      options: ['Compte client inexistant ou bloqué', 'Terminal sans liaison radio', 'Carte non activée par son porteur', 'Plafond mensuel atteint'],
      correctIndex: 0,
      explanation: 'DE39=76 indique généralement \'Invalid/non-existent account\' (compte bancaire non trouvé ou clôturé).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-063',
      category: 'Codes DE39',
      question: 'Quelle est la conséquence pour le commerçant si une transaction autorisée avec DE39=00 fait l\'objet d\'un MTI 0420 ultérieur ?',
      options: ['Le commerçant reçoit un double paiement', 'L\'autorisation est annulée et aucun règlement financier ne sera opéré au profit du commerçant', 'La banque émettrice est mise en demeure', 'Le TPE est bloqué 24 heures'],
      correctIndex: 1,
      explanation: 'Le Reversal (0420) annule l\'autorisation accordée (00) : la transaction est annulée et ne figurera pas dans la compensation financière.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-064',
      category: 'Codes DE39',
      question: 'Quel code DE39 signale qu\'une transaction nécessite une authentification forte du client (SCA - Strong Customer Authentication) selon la DSP2 ?',
      options: ['1A ou 65', '00', '51', '91'],
      correctIndex: 0,
      explanation: 'Le code 1A (Soft Decline) signale au marchand de relancer la transaction en déclenchant le protocole 3D Secure pour authentification SCA.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-065',
      category: 'Codes DE39',
      question: 'Que doit faire le système frontal d\'un switch quand une liaison vers une banque partenaire tombe et renvoie systématiquement DE39=91 ?',
      options: ['Continuer d\'envoyer toutes les transactions pour forcer la connexion', 'Activer le Stand-In Processing (STIP) ou basculer vers un lien de secours et renvoyer un code propre', 'Déconnecter immédiatement tous les commerçants du réseau', 'Mettre les montants à zéro'],
      correctIndex: 1,
      explanation: 'En cas d\'indisponibilité persistante d\'un émetteur, le switch doit engager les règles de Stand-In Processing (STIP) dans les limites autorisées ou router sur le lien secondaire.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-066',
      category: 'Codes DE39',
      question: 'Que signifie le code DE39 = \'89\' (Bad Terminal ID) ?',
      options: ['Le numéro de série du terminal a changé', 'Le TID (DE 41) transmis n\'est pas configuré ou est non autorisé dans la base acquéreur', 'Le terminal est déconnecté du secteur', 'L\'écran du terminal est cassé'],
      correctIndex: 1,
      explanation: 'DE39=89 indique un identifiant de terminal inconnu ou invalide pour l\'acquéreur destinataire.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-067',
      category: 'Codes DE39',
      question: 'Que signifie le code DE39 = \'90\' (Cut-off in process) ?',
      options: ['La ligne téléphonique a été coupée physiquement', 'Le système bancaire émetteur effectue sa bascule de clôture comptable journalière (arrêté comptable)', 'Le client a résilié son contrat', 'Le serveur de backup a été détruit'],
      correctIndex: 1,
      explanation: 'DE39=90 signale que le système hôte est en cours d\'arrêté comptable de fin de journée et ne peut traiter les autorisations pendant cette brève bascule.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-068',
      category: 'Codes DE39',
      question: 'Quel code DE39 indique qu\'une transaction dépasse le montant unitaire maximal autorisé pour une carte bancaire ?',
      options: ['61', '13', '51', '67'],
      correctIndex: 0,
      explanation: 'DE39=61 couvre à la fois le dépassement des limites cumulées et le dépassement du montant unitaire plafond autorisé pour le produit.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-069',
      category: 'Codes DE39',
      question: 'Que signifie le code DE39 = \'25\' (Unable to locate record on file) ?',
      options: ['Le reçu papier est introuvable', 'L\'enregistrement de la transaction ou de la carte est introuvable dans la base de données de l\'hôte', 'Le commerçant n\'est pas répertorié au registre du commerce', 'Le client a déménagé'],
      correctIndex: 1,
      explanation: 'DE39=25 est souvent retourné lors d\'une tentative d\'annulation, de réconciliation ou de capture pour une transaction introuvable dans l\'historique de l\'hôte.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-070',
      category: 'Codes DE39',
      question: 'Lorsqu\'une transaction e-commerce échoue avec DE39 = \'82\' (Incorrect CVV/iCVV), quelle est l\'origine du problème ?',
      options: ['Le porteur a mal saisi les 3 chiffres au dos de sa carte ou la banque émettrice a calculé une mauvaise valeur de référence', 'Le terminal n\'est pas relié à la terre', 'La date de naissance est incorrecte', 'L\'ordinateur a un virus'],
      correctIndex: 0,
      explanation: 'DE39=82 indique que le cryptogramme de contrôle visuel (CVV2/CVC2) renseigné ne correspond pas à la valeur attendue par l\'émetteur.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-071',
      category: 'Cryptographie EMV',
      question: 'Quel tag EMV TLV contient le cryptogramme de transaction ARQC généré par la puce ?',
      options: ['Tag 82', 'Tag 95', 'Tag 9F26', 'Tag 5F2A'],
      correctIndex: 2,
      explanation: 'Le Tag 9F26 contient l\'Application Cryptogram (ARQC - Authorization Request Cryptogram) sur 8 octets.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-072',
      category: 'Cryptographie EMV',
      question: 'Que contient le tag EMV 95 (Terminal Verification Results - TVR) ?',
      options: ['Le montant autorisé en devise locale', 'Les indicateurs de contrôle de sécurité (hors-ligne, échec PIN, carte expirée)', 'Le nom complet du porteur', 'La clé de travail ZPK de l\'acquéreur'],
      correctIndex: 1,
      explanation: 'Le TVR (Tag 95) est un masque de 5 octets où chaque bit documente une anomalie constatée durant la transaction.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-073',
      category: 'Cryptographie EMV',
      question: 'Que signifie l\'acronyme ARQC en technologie de paiement EMV ?',
      options: ['Automated Real-time Query Code', 'Authorization Request Cryptogram', 'Acquirer Risk Quality Certificate', 'Account Routing Quick Confirmation'],
      correctIndex: 1,
      explanation: 'L\'ARQC (Authorization Request Cryptogram) est le cryptogramme calculé par la puce avec sa clé secrète MK_AC pour demander une autorisation en ligne.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-074',
      category: 'Cryptographie EMV',
      question: 'Quel cryptogramme est généré par la puce lorsqu\'elle approuve une transaction hors-ligne (Offline) ?',
      options: ['ARQC', 'TC (Transaction Certificate)', 'AAC (Application Authentication Cryptogram)', 'AAR'],
      correctIndex: 1,
      explanation: 'Le TC (Transaction Certificate) est généré par la puce lorsque la transaction est approuvée hors-ligne sans appel au centre d\'autorisation.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-075',
      category: 'Cryptographie EMV',
      question: 'Quel cryptogramme est émis par la puce quand elle refuse formellement la transaction (Rejet de la carte) ?',
      options: ['TC', 'ARQC', 'AAC (Application Authentication Cryptogram)', 'ARP'],
      correctIndex: 2,
      explanation: 'L\'AAC (Application Authentication Cryptogram) certifie que la puce a refusé la transaction suite à un contrôle de sécurité interne non satisfait.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-076',
      category: 'Cryptographie EMV',
      question: 'Quel tag EMV TLV transporte le Cryptogram Information Data (CID) spécifiant le type de cryptogramme produit ?',
      options: ['Tag 9F27', 'Tag 9F26', 'Tag 9F36', 'Tag 9F10'],
      correctIndex: 0,
      explanation: 'Le Tag 9F27 (CID) sur 1 octet indique si le cryptogramme est un ARQC (0x80), un TC (0x40) ou un AAC (0x00).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-077',
      category: 'Cryptographie EMV',
      question: 'Quel tag EMV TLV transporte l\'Application Transaction Counter (ATC) de la puce ?',
      options: ['Tag 9F36', 'Tag 9F1A', 'Tag 9F37', 'Tag 9A'],
      correctIndex: 0,
      explanation: 'Le Tag 9F36 (ATC) est un compteur incrémenté de 1 à chaque transaction par la puce, empêchant les attaques par rejeu.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-078',
      category: 'Cryptographie EMV',
      question: 'Que contient le tag EMV 9F37 (Unpredictable Number - UN) ?',
      options: ['Le numéro de série de la carte', 'Un nombre aléatoire de 4 octets généré par le terminal pour garantir l\'unicité de chaque calcul de cryptogramme', 'Le solde bancaire', 'Le temps écoulé depuis la dernière mise à jour'],
      correctIndex: 1,
      explanation: 'L\'Unpredictable Number (Tag 9F37) est un aléa généré par le terminal intégré dans le calcul de l\'ARQC pour interdire tout rejeu de transaction.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-079',
      category: 'Cryptographie EMV',
      question: 'Quel tag EMV transporte les données de l\'émetteur propres à l\'application (Issuer Application Data - IAD) ?',
      options: ['Tag 9F10', 'Tag 9F02', 'Tag 82', 'Tag 84'],
      correctIndex: 0,
      explanation: 'Le Tag 9F10 (Issuer Application Data - IAD) contient des informations propriétaires de l\'émetteur (méthode de dérivation de clé, résultats de vérification interne du PIN).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-080',
      category: 'Cryptographie EMV',
      question: 'Quel tag EMV contient le montant autorisé au format binaire ou numérique BCD sur 6 octets ?',
      options: ['Tag 9F02', 'Tag 9F03', 'Tag 9F1A', 'Tag 5F2A'],
      correctIndex: 0,
      explanation: 'Le Tag 9F02 (Amount, Authorized) transporte le montant de la transaction au format BCD sur 6 octets (12 chiffres).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-081',
      category: 'Cryptographie EMV',
      question: 'Que contient le tag EMV 9B (Transaction Status Information - TSI) ?',
      options: ['Le code PIN en clair', 'Les indicateurs d\'étapes de traitement EMV franchies par le terminal (authentification hors-ligne effectuée, gestion des risques effectuée)', 'Le nom de l\'enseigne', 'La version du firmware du terminal'],
      correctIndex: 1,
      explanation: 'Le TSI (Tag 9B sur 2 octets) indique quelles fonctions clés d\'EMV ont été exécutées avec succès durant la session.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-082',
      category: 'Cryptographie EMV',
      question: 'Quel tag EMV contient l\'AIP (Application Interchange Profile) sur 2 octets ?',
      options: ['Tag 82', 'Tag 9F06', 'Tag 8A', 'Tag 95'],
      correctIndex: 0,
      explanation: 'Le Tag 82 (AIP) indique les capacités fonctionnelles supportées par la puce (ex: support SDA, DDA, CDA, Cardholder Verification).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-083',
      category: 'Cryptographie EMV',
      question: 'Quel tag EMV contient l\'Authorization Response Code (ARC) renvoyé par l\'émetteur dans le DE55 vers la puce ?',
      options: ['Tag 8A', 'Tag 8E', 'Tag 9F26', 'Tag 91'],
      correctIndex: 0,
      explanation: 'Le Tag 8A (ARC) contient sur 2 caractères la réponse de l\'émetteur (ex: \'00\' pour accord, \'05\' pour refus) communiquée à la carte pour sa 2ème décision (2nd Gen AC).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-084',
      category: 'Cryptographie EMV',
      question: 'Quel tag EMV transporte l\'Issuer Authentication Data contenant l\'ARPC généré par la banque émettrice ?',
      options: ['Tag 91', 'Tag 8A', 'Tag 71', 'Tag 72'],
      correctIndex: 0,
      explanation: 'Le Tag 91 (Issuer Authentication Data) contient l\'ARPC (Authorization Response Cryptogram) prouvant à la carte que la réponse provient authentiquement de son émetteur.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-085',
      category: 'Cryptographie EMV',
      question: 'Quelle est la différence entre SDA (Static Data Authentication) et DDA (Dynamic Data Authentication) en EMV ?',
      options: ['SDA vérifie uniquement des données statiques signées et ne protège pas contre le clonage de puce ; DDA génère une signature dynamique par transaction à l\'aide d\'une clé RSA interne à la carte', 'SDA est sans contact, DDA est avec contact', 'SDA utilise AES, DDA utilise DES', 'Il n\'y a aucune différence technique'],
      correctIndex: 0,
      explanation: 'DDA protège contre le clonage grâce à une paire de clés asymétriques RSA propre à chaque carte, contrairement à SDA qui authentifie uniquement des données fixes.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-086',
      category: 'Cryptographie EMV',
      question: 'Que permet l\'authentification combinée CDA (Combined DDA/Application Cryptogram Generation) ?',
      options: ['De vérifier la validité de la signature RSA dynamique en même temps que la production du cryptogramme ARQC/TC, évitant les attaques de type Man-in-the-Middle', 'D\'accélérer la connexion Wi-Fi', 'De supprimer le code PIN', 'D\'autoriser le découvert illimité'],
      correctIndex: 0,
      explanation: 'CDA intègre le cryptogramme de transaction dans la signature dynamique RSA, garantissant qu\'aucune entité intermédiaire n\'a altéré la transaction entre la décision et la fin de session.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-087',
      category: 'Cryptographie EMV',
      question: 'Quel tag EMV contient le Dedicated File Name (DF Name / Application Identifier - AID) ?',
      options: ['Tag 84', 'Tag 4F', 'Tag 50', 'Tag 87'],
      correctIndex: 0,
      explanation: 'Le Tag 84 (DF Name) ou Tag 4F identifie l\'application bancaire sélectionnée dans la puce (ex: A0000000031010 pour Visa Credit).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-088',
      category: 'Cryptographie EMV',
      question: 'Quel est l\'AID EMV standard pour une application de débit/crédit Visa ?',
      options: ['A0000000031010', 'A0000000041010', 'A00000002501', 'A0000001523010'],
      correctIndex: 0,
      explanation: 'A0000000031010 est le RID/PIX de Visa (RID=A000000003, PIX=1010).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-089',
      category: 'Cryptographie EMV',
      question: 'Quel est l\'AID EMV standard pour une carte Mastercard de paiement ?',
      options: ['A0000000031010', 'A0000000041010', 'A00000006510', 'A0000002771010'],
      correctIndex: 1,
      explanation: 'A0000000041010 est l\'Application Identifier officiel de Mastercard (RID=A000000004).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-090',
      category: 'Cryptographie EMV',
      question: 'Quel tag EMV transporte le Cardholder Name (Nom et prénom du titulaire de la carte) ?',
      options: ['Tag 5F20', 'Tag 5F24', 'Tag 5F28', 'Tag 5F30'],
      correctIndex: 0,
      explanation: 'Le Tag 5F20 transporte le nom du titulaire sous forme de chaîne ASCII.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-091',
      category: 'Cryptographie EMV',
      question: 'Quel tag EMV contient l\'Application Expiration Date au format YYMMDD ?',
      options: ['Tag 5F24', 'Tag 5F25', 'Tag 5F34', 'Tag 9A'],
      correctIndex: 0,
      explanation: 'Le Tag 5F24 contient la date d\'expiration de l\'application de la carte (format BCD YYMMDD).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-092',
      category: 'Cryptographie EMV',
      question: 'Quel tag EMV spécifie le Card Sequence Number (PAN Sequence Number - PSN) ?',
      options: ['Tag 5F34', 'Tag 5A', 'Tag 8C', 'Tag 9F08'],
      correctIndex: 0,
      explanation: 'Le Tag 5F34 identifie le numéro de séquence de la carte (PSN), permettant de distinguer deux cartes réémises avec le même PAN.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-093',
      category: 'Cryptographie EMV',
      question: 'Quel tag EMV transporte le Primary Account Number (PAN) extrait de la puce ?',
      options: ['Tag 5A', 'Tag 57', 'Tag 82', 'Tag 9F02'],
      correctIndex: 0,
      explanation: 'Le Tag 5A transporte le PAN compressé en BCD.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-094',
      category: 'Cryptographie EMV',
      question: 'Que contient le tag EMV 8E (Cardholder Verification Method List - CVM List) ?',
      options: ['La liste ordonnée des méthodes de vérification du porteur acceptées par la carte (PIN en ligne, PIN hors-ligne en clair, PIN chiffré, Signature, Pas de CVM)', 'Les montants des plafonds', 'La liste des pays interdits', 'Les adresses IP autorisées'],
      correctIndex: 0,
      explanation: 'La CVM List (Tag 8E) dicte la priorité des vérifications du porteur selon le montant et la devise.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-095',
      category: 'Cryptographie EMV',
      question: 'Quelle est la méthode de chiffrement symétrique historiquement et majoritairement utilisée pour le calcul de l\'ARQC ?',
      options: ['Triple-DES (TDES / 3DES 2-clés ou 3-clés en mode CBC-MAC)', 'RSA 4096 bits', 'ChaCha20', 'Blowfish'],
      correctIndex: 0,
      explanation: 'EMV utilise historiquement le Triple-DES (TDES) avec dérivation de clé de session (Session Key) pour calculer le CBC-MAC de l\'ARQC.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-096',
      category: 'Cryptographie EMV',
      question: 'Quel algorithme cryptographique plus moderne remplace progressivement le 3DES dans les dernières spécifications EMV (EMV Contactless & EMV 4.4) ?',
      options: ['AES (Advanced Encryption Standard - 128/256 bits)', 'RC4', 'MD5', 'DES simple 56 bits'],
      correctIndex: 0,
      explanation: 'L\'AES-128 ou 256 bits remplace le 3DES pour offrir une résistance cryptographique conforme aux recommandations du NIST et de PCI-SSC.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-097',
      category: 'Cryptographie EMV',
      question: 'Que contient le tag EMV 9F34 (Cardholder Verification Method Results - CVM Results) ?',
      options: ['Le code PIN saisi par le porteur en clair', 'Le résultat et la méthode effectivement appliquée lors de la vérification du porteur (ex: PIN offline vérifié avec succès)', 'Le résultat de l\'interrogation de solvabilité', 'Le numéro de caisse'],
      correctIndex: 1,
      explanation: 'Le Tag 9F34 (3 octets) documente la règle CVM choisie, la condition et si la vérification a réussi ou échoué.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-098',
      category: 'Cryptographie EMV',
      question: 'Dans le TVR (Tag 95), que signifie un octet 1 avec le bit 8 à 1 (0x80) ?',
      options: ['Transaction approuvée d\'office', 'Authentification hors-ligne des données (Offline Data Authentication - ODA) non réalisée', 'Carte volée', 'Émetteur injoignable'],
      correctIndex: 1,
      explanation: 'Dans le premier octet du TVR, le bit 8 signifie \'Offline data authentication was not performed\'.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-099',
      category: 'Cryptographie EMV',
      question: 'Que contient le tag EMV 9F1E (Interface Device Serial Number) ?',
      options: ['Le numéro de série physique du lecteur ou du terminal de paiement', 'Le numéro de série de la puce', 'Le numéro du commutateur', 'L\'adresse MAC de la passerelle'],
      correctIndex: 0,
      explanation: 'Le Tag 9F1E contient sur 8 caractères alphanumériques le numéro de série unique du terminal (IFD Serial Number).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-100',
      category: 'Cryptographie EMV',
      question: 'Quel tag EMV contient le Terminal Country Code selon la norme ISO 3166 ?',
      options: ['Tag 9F1A', 'Tag 5F2A', 'Tag 9A', 'Tag 9C'],
      correctIndex: 0,
      explanation: 'Le Tag 9F1A identifie le code pays numérique du terminal (ex: 0250 pour la France).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-101',
      category: 'Cryptographie EMV',
      question: 'Quel tag EMV contient la date de la transaction au niveau terminal (Transaction Date - YYMMDD) ?',
      options: ['Tag 9A', 'Tag 9C', 'Tag 9F02', 'Tag 9F21'],
      correctIndex: 0,
      explanation: 'Le Tag 9A transporte la date locale de la transaction au format BCD YYMMDD.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-102',
      category: 'Cryptographie EMV',
      question: 'Quel tag EMV contient l\'heure de la transaction (Transaction Time - HHMMSS) ?',
      options: ['Tag 9F21', 'Tag 9A', 'Tag 9C', 'Tag 9F36'],
      correctIndex: 0,
      explanation: 'Le Tag 9F21 transporte l\'heure locale de la transaction au format BCD HHMMSS.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-103',
      category: 'Cryptographie EMV',
      question: 'Quel tag EMV indique le type de transaction (Transaction Type) correspondant aux 2 premiers chiffres du Processing Code ?',
      options: ['Tag 9C', 'Tag 9A', 'Tag 82', 'Tag 9F03'],
      correctIndex: 0,
      explanation: 'Le Tag 9C transporte le type d\'opération (ex: \'00\' pour achat marchand, \'01\' pour retrait d\'espèces).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-104',
      category: 'Cryptographie EMV',
      question: 'Que contient le tag EMV 71 et 72 (Issuer Scripts) transmis dans le DE55 lors d\'une réponse 0110/0210 ?',
      options: ['Des scripts et commandes APDU envoyés par l\'émetteur pour mettre à jour la puce (débloquer le PIN, modifier les plafonds, bloquer l\'application)', 'Des publicités à afficher sur le ticket', 'Des clés de déchiffrement Wi-Fi', 'L\'adresse du site web de la banque'],
      correctIndex: 0,
      explanation: 'Les Tags 71 et 72 contiennent des commandes de script d\'émetteur (Issuer Scripts 1 et 2) exécutées post-autorisation sur la carte.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-105',
      category: 'Cryptographie EMV',
      question: 'Comment la puce EMV dérive-t-elle sa clé de session (Session Key) pour chaque calcul d\'ARQC ?',
      options: ['En combinant sa clé maîtresse d\'application (MK_AC) avec son compteur de transaction (ATC) et l\'aléa du terminal', 'En demandant la clé au terminal par Bluetooth', 'En lisant la piste magnétique', 'La clé de session est fixe et gravée à la fabrication'],
      correctIndex: 0,
      explanation: 'La puce utilise sa Master Key MK_AC pour dériver dynamiquement une clé unique par transaction basée sur l\'Application Transaction Counter (ATC).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-106',
      category: 'Sécurité HSM & Clés',
      question: 'Quelle clé cryptographique est utilisée pour chiffrer le PIN Block entre le terminal et le serveur d\'autorisation ?',
      options: ['LMK (Local Master Key)', 'TPK / ZPK (Terminal / Zone PIN Key)', 'CVK (Card Verification Key)', 'BDK DUKPT'],
      correctIndex: 1,
      explanation: 'La ZPK (Zone PIN Key) ou TPK (Terminal PIN Key) assure le chiffrement symétrique 3DES/AES des PIN blocks en transit.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-107',
      category: 'Sécurité HSM & Clés',
      question: 'Qu\'est-ce qu\'une LMK (Local Master Key) dans un module de sécurité matériel (HSM) bancaire ?',
      options: ['Une clé publique stockée sur internet', 'Une clé maîtresse propriétaire interne au HSM, jamais exportée en clair, servant à chiffrer toutes les autres clés stockées en base', 'Une clé jetable à usage unique', 'Une clé de chiffrement du disque dur du serveur'],
      correctIndex: 1,
      explanation: 'La LMK est la clé racine inviolable résidant dans la mémoire sécurisée du HSM (Tamper-responsive memory), servant à protéger toutes les clés de travail.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-108',
      category: 'Sécurité HSM & Clés',
      question: 'Quelle est la fonction principale d\'un HSM (Hardware Security Module) de paiement (ex: Thales payShield, Atos Cryptsys) ?',
      options: ['Héberger le site web de la banque', 'Exécuter les calculs cryptographiques sensibles (vérification PIN, calcul ARQC, dérivation de clés) dans un boîtier sécurisé anti-intrusion', 'Remplacer le switch ISO 8583', 'Stocker les relevés de compte des clients'],
      correctIndex: 1,
      explanation: 'Le HSM offre un environnement matériel hautement certifié (FIPS 140-2 Niveau 3/4) pour exécuter la cryptographie financière sans risque d\'exfiltration.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-109',
      category: 'Sécurité HSM & Clés',
      question: 'Dans le protocole DUKPT (Derived Unique Key Per Transaction), comment est garantie la sécurité des transactions ?',
      options: ['Une nouvelle clé de chiffrement unique est dérivée pour chaque transaction et immédiatement détruite après usage', 'Une seule clé universelle est partagée entre tous les terminaux du monde', 'Le chiffrement change tous les lundis matin', 'La clé dépend de la couleur de la carte'],
      correctIndex: 0,
      explanation: 'DUKPT calcule une clé éphémère différente pour chaque transaction à partir d\'un compteur KSN. Même si une clé est compromise, elle ne compromet ni le passé ni le futur.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-110',
      category: 'Sécurité HSM & Clés',
      question: 'Qu\'est-ce que le KSN (Key Serial Number) dans un système utilisant la gestion de clés DUKPT ?',
      options: ['Le mot de passe administrateur du TPE', 'Un identifiant public composé du Base Derivation Key ID, de l\'ID du terminal et du compteur séquentiel de transaction', 'Le numéro de compte du porteur', 'Le code postal du commerçant'],
      correctIndex: 1,
      explanation: 'Le KSN (Key Serial Number sur 10 octets) permet au HSM récepteur de savoir quelle BDK utiliser et combien d\'itérations appliquer pour régénérer la clé exacte.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-111',
      category: 'Sécurité HSM & Clés',
      question: 'Quel format standard de PIN Block (ISO 9564) combine le code secret PIN avec les 12 chiffres de droite du PAN (hors clé de contrôle) ?',
      options: ['Format ISO 9564-1 Format 0 (équivalent ANSI X9.8)', 'Format ISO 9564-1 Format 1', 'Format ISO 9564-1 Format 2', 'Format ISO 9564-1 Format 3'],
      correctIndex: 0,
      explanation: 'Le Format 0 effectue un XOR entre le bloc de PIN et le bloc de PAN pour lier mathématiquement le PIN au compte bancaire du porteur.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-112',
      category: 'Sécurité HSM & Clés',
      question: 'Quelle clé symétrique est utilisée pour transporter de manière sécurisée d\'autres clés entre deux institutions (Key Encryption Key) ?',
      options: ['ZMK (Zone Master Key)', 'CVK (Card Verification Key)', 'PVK (PIN Verification Key)', 'MK_AC'],
      correctIndex: 0,
      explanation: 'La ZMK (Zone Master Key) est une clé de chiffrement de clés (KEK) partagée entre deux entités pour chiffrer les clés opérationnelles (ZPK, ZAK) en transit.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-113',
      category: 'Sécurité HSM & Clés',
      question: 'Quelle clé est utilisée par l\'émetteur pour vérifier le cryptogramme de carte CVV/CVC lors des paiements piste ou en ligne ?',
      options: ['CVK (Card Verification Key)', 'ZPK', 'TPK', 'LMK'],
      correctIndex: 0,
      explanation: 'La CVK (Card Verification Key - paire de clés DES) sert à calculer et vérifier les codes CVV, CVC et CVV2.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-114',
      category: 'Sécurité HSM & Clés',
      question: 'Quelle clé est traditionnellement utilisée par un émetteur pour vérifier un PIN Offset selon la méthode IBM 3624 ?',
      options: ['PVK (PIN Verification Key)', 'ZMK', 'ZAK', 'PEK'],
      correctIndex: 0,
      explanation: 'La PVK (PIN Verification Key) sert à dériver le Natural PIN à partir du PAN et à le comparer avec le PIN Offset stocké.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-115',
      category: 'Sécurité HSM & Clés',
      question: 'Qu\'est-ce que le KCV (Key Check Value) dans l\'administration des clés cryptographiques ?',
      options: ['Une taxe sur les clés de chiffrement', 'Le résultat du chiffrement d\'un bloc de zéros (0x00...00) par la clé, servant d\'empreinte de contrôle (checksum) à 6 caractères hexadécimaux', 'La date de création de la clé', 'La longueur de la clé en bits'],
      correctIndex: 1,
      explanation: 'Le KCV (Key Check Value) permet aux deux administrateurs de vérifier qu\'ils possèdent la même clé sans jamais échanger la clé elle-même.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-116',
      category: 'Sécurité HSM & Clés',
      question: 'Quelle exigence stricte de la norme PCI-DSS concerne le stockage du code PIN et du cryptogramme CVV2 après autorisation ?',
      options: ['Ils doivent être conservés dans un fichier texte crypté', 'Leur stockage après autorisation est STRICTEMENT INTERDIT, même sous forme chiffrée', 'Ils doivent être conservés au moins 5 ans à des fins fiscales', 'Ils doivent être imprimés sur du papier sécurisé'],
      correctIndex: 1,
      explanation: 'La norme PCI-DSS interdit formellement la conservation des données d\'authentification sensibles (SAD : PIN Block, CVV2, données complètes de la piste) après autorisation.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-117',
      category: 'Sécurité HSM & Clés',
      question: 'Quel est le principe du \'Dual Control / Split Knowledge\' imposé pour la manipulation des clés maîtresses LMK et ZMK ?',
      options: ['Chaque clé est divisée en plusieurs composants détenus par des officiers de sécurité distincts, aucun n\'ayant la clé complète à lui seul', 'Il faut deux ordinateurs identiques pour allumer le HSM', 'Le serveur doit avoir deux cartes réseau', 'Il faut deux mots de passe pour se connecter à Windows'],
      correctIndex: 0,
      explanation: 'Le principe de contrôle conjoint (Dual Control) garantit qu\'aucun individu isolé ne peut connaître ou reconstituer une clé critique.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-118',
      category: 'Sécurité HSM & Clés',
      question: 'Que se passe-t-il si un attaquant tente d\'ouvrir physiquement le châssis d\'un HSM bancaire certifié FIPS 140-2 niveau 3 ?',
      options: ['Le HSM envoie un e-mail à la police', 'Les circuits de détection physique (Tamper Detection) effacent instantanément et irréversiblement les clés LMK de la mémoire (Zeroization)', 'Le HSM verrouille ses disques mais garde les clés', 'Une alarme sonore retentit dans la pièce'],
      correctIndex: 1,
      explanation: 'La fonction d\'effacement automatique (Zeroization) détruit électriquement toutes les clés en mémoire en quelques microsecondes dès la détection d\'une effraction.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-119',
      category: 'Sécurité HSM & Clés',
      question: 'Quelle clé est utilisée pour générer et vérifier le MAC (Message Authentication Code) sur un message financier ISO 8583 ?',
      options: ['ZAK (Zone Authentication Key) ou TAK (Terminal Authentication Key)', 'ZPK', 'CVK', 'LMK'],
      correctIndex: 0,
      explanation: 'La ZAK (ou TAK) est dédiée au calcul du code d\'intégrité MAC (DE 64 / DE 128) protégeant les trames contre toute falsification en transit.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-120',
      category: 'Sécurité HSM & Clés',
      question: 'Dans le calcul d\'un PIN Offset selon l\'algorithme IBM 3624, quelle opération est réalisée ?',
      options: ['Une simple addition entre le PIN et le PAN', 'Le chiffrement du PAN par la PVK, suivi d\'une décimalisation pour obtenir le Natural PIN, duquel on soustrait le code PIN choisi pour obtenir l\'Offset', 'Une division euclidienne par 12', 'Une concaténation de dates'],
      correctIndex: 1,
      explanation: 'L\'algorithme IBM 3624 chiffre le PAN avec la PVK, applique une table de décimalisation pour produire le Natural PIN, puis calcule l\'Offset = (PIN choisi - Natural PIN) modulo 10.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-121',
      category: 'Sécurité HSM & Clés',
      question: 'Qu\'est-ce qu\'une attaque par \'Padding Oracle\' contre un système de chiffrement en mode CBC ?',
      options: ['Une attaque qui exploite les messages d\'erreur détaillés sur le remplissage (padding) pour déchiffrer le contenu sans connaître la clé', 'Une attaque qui devine le mot de passe utilisateur', 'Une surcharge de mémoire vive', 'Une coupure d\'alimentation électrique'],
      correctIndex: 0,
      explanation: 'Une attaque par Oracle de Padding exploite les réponses différenciées du serveur sur le padding PKCS#7 pour retrouver octet par octet le texte en clair.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-122',
      category: 'Sécurité HSM & Clés',
      question: 'Pourquoi l\'algorithme DES simple (56 bits de clé) est-il totalement banni de l\'industrie des cartes de paiement ?',
      options: ['Parce qu\'il ne fonctionne pas sur les serveurs 64 bits', 'Parce que sa clé de 56 bits est cassable en quelques heures par recherche exhaustive (brute-force) moderne', 'Parce qu\'il utilise trop de bande passante réseau', 'Parce qu\'il n\'est pas compatible avec l\'Euro'],
      correctIndex: 1,
      explanation: 'L\'espace de clés du DES simple (2^56) est devenu ridiculement vulnérable face aux puissances de calcul contemporaines.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-123',
      category: 'Sécurité HSM & Clés',
      question: 'Quelle est la taille de clé effective du Triple-DES 2-clés (2TDES) face aux attaques Meet-in-the-Middle ?',
      options: ['112 bits', '80 bits effectifs en raison des attaques par collision / Sweet32', '168 bits', '256 bits'],
      correctIndex: 1,
      explanation: 'En raison des attaques Meet-in-the-Middle et des collisions sur les blocs de 64 bits (attaque Sweet32), le 2TDES n\'offre plus qu\'une sécurité théorique d\'environ 80-112 bits, justifiant son abandon pour l\'AES.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-124',
      category: 'Sécurité HSM & Clés',
      question: 'Dans une architecture acquéreur, quel rôle joue le composant PED (PIN Entry Device) certifié PCI-PTS ?',
      options: ['C\'est le clavier sécurisé où le client tape son PIN, garantissant le chiffrement immédiat à la source avant toute transmission au microprocesseur hôte', 'C\'est l\'écran tactile publicitaire', 'C\'est l\'imprimante thermique', 'C\'est le modem 4G'],
      correctIndex: 0,
      explanation: 'Le PED certifié PCI-PTS garantit que les touches du clavier sont scellées et que le PIN est instantanément chiffré dans une puce sécurisée.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-125',
      category: 'Sécurité HSM & Clés',
      question: 'Qu\'est-ce qu\'une table de décimalisation dans un HSM bancaire ?',
      options: ['Une table qui convertit les devises étrangères', 'Un tableau de 16 chiffres (0 à 9) permettant de convertir le résultat hexadécimal (0-F) d\'un chiffrement DES en un PIN numérique à 4 chiffres', 'Une table de calcul des commissions d\'interchange', 'Un tableau des fuseaux horaires'],
      correctIndex: 1,
      explanation: 'La table de décimalisation mappe les chiffres hexadécimaux A-F vers des chiffres décimaux 0-9 lors de la génération de PINs.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-126',
      category: 'Sécurité HSM & Clés',
      question: 'Pourquoi les tables de décimalisation doivent-elles être protégées contre toute modification illégitime dans un HSM ?',
      options: ['Pour éviter les bugs d\'arrondi de centimes', 'Parce qu\'une table modifiée permet à un attaquant de retrouver un code PIN en très peu d\'essais via une attaque par substitution (Decimalisation Attack)', 'Pour respecter la langue française', 'Parce qu\'elles prennent trop de place en RAM'],
      correctIndex: 1,
      explanation: 'Une attaque par table de décimalisation permet à un initié malveillant de deviner un code PIN en manipulant les permutations autorisées par l\'API du HSM.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-127',
      category: 'Sécurité HSM & Clés',
      question: 'Quelle norme de l\'industrie régit la sécurité physique et logique des terminaux de paiement (TPE/GAB) ?',
      options: ['PCI-DSS', 'PCI-PTS (PIN Transaction Security)', 'PCI-PA-DSS', 'ISO 9001'],
      correctIndex: 1,
      explanation: 'La norme PCI-PTS (PIN Transaction Security) évalue la résistance des matériels contre les écoutes de touches, le perçage et l\'injection de code malveillant.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-128',
      category: 'Sécurité HSM & Clés',
      question: 'Quel protocole d\'échange de clés asymétrique est couramment utilisé pour charger une clé initiale dans un terminal de paiement sans contact physique (Remote Key Loading - RKL) ?',
      options: ['Certificats RSA et enveloppes PKCS#7 ou protocole Diffie-Hellman', 'FTP non sécurisé', 'Telnet', 'SMS chiffré'],
      correctIndex: 0,
      explanation: 'Le RKL (Remote Key Loading) utilise la cryptographie asymétrique RSA/ECC pour injecter à distance la clé initiale sous forme d\'enveloppe chiffrée signée.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-129',
      category: 'Sécurité HSM & Clés',
      question: 'Qu\'est-ce que le \'Key Rollover\' dans la gestion opérationnelle d\'un switch monétique ?',
      options: ['La suppression brutale de toutes les clés de la banque', 'Le renouvellement périodique programmé des clés de chiffrement de travail (ZPK, ZAK) pour limiter la quantité de données protégées par une même clé', 'La copie des clés sur une clé USB', 'Le changement d\'adresse IP du serveur HSM'],
      correctIndex: 1,
      explanation: 'La rotation des clés (Key Rollover) limite la cryptanalyse et respecte les normes de sécurité en renouvelant fréquemment les clés de session.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-130',
      category: 'Sécurité HSM & Clés',
      question: 'Quel algorithme de hachage est formellement interdit par PCI-DSS pour la signature ou l\'intégrité des messages de paiement ?',
      options: ['SHA-256', 'SHA-512', 'MD5 et SHA-1', 'SHA-3'],
      correctIndex: 2,
      explanation: 'MD5 et SHA-1 sont totalement prohibés en raison de collisions cryptographiques démontrées dans la pratique.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-131',
      category: 'Sécurité HSM & Clés',
      question: 'Que désigne le \'PIN Translation\' réalisé par un switch monétique connecté à plusieurs banques ?',
      options: ['La traduction du PIN en plusieurs langues', 'Le déchiffrement du PIN Block reçu sous la clé de l\'acquéreur (TPK/ZPK1) et son ré-encodage immédiat sous la clé de l\'émetteur (ZPK2) à l\'intérieur du HSM sans jamais l\'exposer en clair', 'L\'envoi du PIN par SMS', 'La sauvegarde du PIN en base SQL'],
      correctIndex: 1,
      explanation: 'La translation de PIN s\'exécute exclusivement dans la mémoire sécurisée du HSM : le PIN entre chiffré sous ZPK_A et ressort chiffré sous ZPK_B sans aucune exposition en clair.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-132',
      category: 'Sécurité HSM & Clés',
      question: 'Dans le format ISO 9564-1 Format 1, quelle caractéristique différencie ce PIN block du Format 0 ?',
      options: ['Il n\'intègre pas le numéro de compte PAN dans son calcul', 'Il utilise 16 chiffres au lieu de 4', 'Il est envoyé en clair', 'Il est réservé aux paiements en Bitcoin'],
      correctIndex: 0,
      explanation: 'Le Format 1 est utilisé quand le PAN n\'est pas disponible ou lors d\'échanges de clés d\'authentification sans liaison au compte.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-133',
      category: 'Sécurité HSM & Clés',
      question: 'Qu\'est-ce que le chiffrement P2PE (Point-to-Point Encryption) validé par le PCI Security Standards Council ?',
      options: ['Un système où les données de carte sont chiffrées dès le lecteur du commerçant et ne sont déchiffrées que dans l\'environnement sécurisé de la passerelle de paiement / acquéreur', 'Un VPN entre le magasin et le commissariat', 'Un câble blindé reliant le TPE à la caisse', 'Un système de paiement par empreinte digitale'],
      correctIndex: 0,
      explanation: 'La norme PCI-P2PE assure que les données de carte voyagent chiffrées de bout en bout et ne peuvent jamais être interceptées dans le système de caisse du commerçant.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-134',
      category: 'Sécurité HSM & Clés',
      question: 'Quelle commande HSM standard Thales/PayShield est couramment utilisée pour vérifier un cryptogramme ARQC émis par une carte EMV ?',
      options: ['Commande \'KQ\' ou \'CC\' (Generate/Verify ARQC/ARPC)', 'Commande \'A0\' (Generate Key)', 'Commande \'BA\' (Diagnostics)', 'Commande \'EE\' (Erase All)'],
      correctIndex: 0,
      explanation: 'La commande \'KQ\' ou \'CC\' demande au HSM de vérifier l\'ARQC à partir de la MK_AC et des données DE55, puis de générer l\'ARPC de retour.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-135',
      category: 'Sécurité HSM & Clés',
      question: 'Quelle est la conséquence d\'une désynchronisation d\'horloge (Time Drift > 5 secondes) entre un serveur frontal et un HSM ?',
      options: ['Le HSM s\'éteint automatiquement', 'Les signatures à base d\'horodatage ou de jetons temporaires et les audits de conformité peuvent être invalidés', 'Le montant des retraits est divisé par deux', 'Tous les PINs sont réinitialisés à 0000'],
      correctIndex: 1,
      explanation: 'L\'intégrité des logs d\'audit et la validité des fenêtres de tolérance temporelles requièrent une synchronisation NTP stricte.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-136',
      category: 'Compensation & Normes',
      question: 'Quelle est la différence fondamentale entre la phase d\'Autorisation et la phase de Compensation (Clearing) ?',
      options: ['L\'autorisation réserve la provision en temps réel ; la compensation échange les fichiers de créances et de dettes entre banques en différé (fin de journée)', 'L\'autorisation se fait par chèque, la compensation par carte', 'L\'autorisation est gérée par le commerçant, la compensation par le client', 'Il n\'y a aucune différence, ce sont des synonymes'],
      correctIndex: 0,
      explanation: 'L\'autorisation valide la solvabilité immédiate. La compensation calcule les soldes nets multilatéraux et procède à l\'échange des écritures comptables.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-137',
      category: 'Compensation & Normes',
      question: 'Qu\'est-ce que le Règlement (Settlement) interbancaire ?',
      options: ['L\'envoi des relevés de compte par la poste', 'Le transfert irrévocable des fonds entre les comptes des banques tenus auprès de la Banque Centrale pour solder leurs positions nettes', 'Le remboursement d\'un commerçant par un client', 'La signature du contrat de carte'],
      correctIndex: 1,
      explanation: 'Le règlement (Settlement) est la phase financière finale où la monnaie centrale est transférée via le système de paiement brut de la Banque Centrale (ex: TARGET2).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-138',
      category: 'Compensation & Normes',
      question: 'Qu\'est-ce que la commission d\'interchange (MIF - Multilateral Interchange Fee) ?',
      options: ['Des frais de port payés à la poste', 'La commission payée par la banque acquéreuse du commerçant à la banque émettrice du porteur sur chaque transaction carte', 'Un pourboire versé au caissier', 'Une taxe sur les distributeurs de billets'],
      correctIndex: 1,
      explanation: 'L\'interchange rémunère la banque émettrice pour la couverture du risque de crédit, la fraude et les coûts de gestion du programme carte.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-139',
      category: 'Compensation & Normes',
      question: 'Quel est le plafond réglementaire européen (Règlement MIF 2015/751) pour la commission d\'interchange sur les cartes de débit grand public ?',
      options: ['0,2 % de la valeur de la transaction', '0,3 %', '1,5 %', '5,0 %'],
      correctIndex: 0,
      explanation: 'Le règlement européen plafonne l\'interchange des cartes de débit à 0,2 % et celui des cartes de crédit à 0,3 % pour le grand public.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-140',
      category: 'Compensation & Normes',
      question: 'Qu\'est-ce qu\'un Chargeback (Répudiation / Rétrofacturation) en monétique de paiement ?',
      options: ['Une panne matérielle sur un serveur de switch', 'La contestation d\'une transaction par l\'émetteur au profit du porteur entraînant la restitution forcée des fonds par l\'acquéreur selon les règles du réseau', 'Une prime accordée aux bons clients', 'Un changement de mot de passe'],
      correctIndex: 1,
      explanation: 'Le Chargeback est le mécanisme normé par Visa/Mastercard permettant à l\'émetteur de reprendre les fonds si une transaction est frauduleuse ou non honorée.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-141',
      category: 'Compensation & Normes',
      question: 'Quel principe de responsabilité (Liability Shift) a été introduit par l\'avènement de la norme EMV ?',
      options: ['Le commerçant est toujours coupable', 'La responsabilité financière des fraudes est transférée à la partie qui n\'a pas migré vers la technologie EMV à puce (ex: commerçant avec lecteur piste uniquement)', 'Les banques centrales paient toutes les fraudes', 'Le client paie 100% de la fraude'],
      correctIndex: 1,
      explanation: 'Le Liability Shift pénalise l\'acteur le moins sécurisé : si une banque émet une carte à puce et que le commerçant force la lecture par piste, la fraude est à la charge de l\'acquéreur.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-142',
      category: 'Compensation & Normes',
      question: 'Qu\'est-ce que le système TARGET2 (ou T2) au sein de la zone Euro ?',
      options: ['Le logiciel antivirus des banques', 'Le système de règlement brut en temps réel (RTGS) opéré par l\'Eurosystème pour les transferts interbancaires de gros montants et le settlement des systèmes cartes', 'Une plateforme de trading de crypto-monnaies', 'Un réseau de distributeurs automatiques de billets'],
      correctIndex: 1,
      explanation: 'TARGET2 est le système RTGS de l\'Eurosystème assurant le règlement immédiat et irrévocable en monnaie de banque centrale.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-143',
      category: 'Compensation & Normes',
      question: 'Qu\'est-ce que la norme ISO 20022 dans les systèmes de paiement modernes ?',
      options: ['Une norme sur la taille physique des cartes plastiques', 'Un standard international de messagerie financière basé sur la syntaxe XML/JSON offrant un modèle de données enrichi pour remplacer progressivement l\'ISO 8583 et les messages SWIFT MT', 'Une norme sur l\'ergonomie des claviers de distributeurs', 'Un label environnemental pour les banques'],
      correctIndex: 1,
      explanation: 'ISO 20022 modernise et unifie la communication financière internationale grâce à des structures de données riches (ex: messages pacs, pain, camt).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-144',
      category: 'Compensation & Normes',
      question: 'Quel est l\'équivalent ISO 20022 du message d\'autorisation monétique ISO 8583 (0100/0200) ?',
      options: ['Message pacs.008', 'Message camt.053', 'Message caaa (Card Administration and Authorization)', 'Message pain.001'],
      correctIndex: 2,
      explanation: 'La famille de messages \'caaa\' (Card Administration and Authorization) sous ISO 20022 standardise les flux d\'autorisation par carte.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-145',
      category: 'Compensation & Normes',
      question: 'Quelle est la fonction d\'une chambre de compensation automatisée (ACH - Automated Clearing House, ex: CORE/STET en France) ?',
      options: ['Réparer les terminaux de paiement', 'Compenser les flux de paiements de masse (virements, prélèvements, chèques, paiements par carte) et calculer les positions nettes multilatérales', 'Fabriquer les cartes bancaires', 'Émettre les billets de banque'],
      correctIndex: 1,
      explanation: 'L\'ACH compense les flux financiers de masse entre banques participantes et transmet les soldes nets résultants à la Banque Centrale pour règlement.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-146',
      category: 'Compensation & Normes',
      question: 'Qu\'est-ce qu\'un schéma de paiement à 4 coins (Four-party payment scheme) ?',
      options: ['Un modèle réunissant Porteur, Banque Émettrice, Acquéreur et Commerçant (ex: Visa, Mastercard, CB)', 'Un terminal de forme carrée', 'Une alliance entre quatre pays européens', 'Un virement avec quatre intermédiaires'],
      correctIndex: 0,
      explanation: 'Le modèle à 4 coins dissocie la relation client-porteur (gérée par l\'émetteur) de la relation commerçant (gérée par l\'acquéreur), avec le schéma au centre.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-147',
      category: 'Compensation & Normes',
      question: 'Quel est un exemple typique de schéma de paiement à 3 coins (Three-party payment scheme) où l\'émetteur et l\'acquéreur sont la même entité ?',
      options: ['American Express ou Diners Club (modèle traditionnel propriétaire)', 'Visa', 'Mastercard', 'Groupement des Cartes Bancaires CB'],
      correctIndex: 0,
      explanation: 'Dans un schéma à 3 coins (propriétaire), l\'opérateur gère directement l\'acquisition des commerçants et l\'émission des cartes aux porteurs.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-148',
      category: 'Compensation & Normes',
      question: 'Qu\'est-ce que le \'Cut-Off\' quotidien d\'un switch ou d\'une passerelle d\'acquisition monétique ?',
      options: ['L\'heure limite de clôture qui sépare les transactions d\'une journée comptable de celles de la journée suivante pour la constitution des fichiers de compensation', 'Une panne d\'électricité générale', 'La coupure de la connexion Internet à minuit', 'L\'expiration du certificat SSL'],
      correctIndex: 0,
      explanation: 'Le Cut-Off fige le lot quotidien de transactions : toutes les opérations après cette heure basculent dans la journée comptable suivante (J+1).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-149',
      category: 'Compensation & Normes',
      question: 'Quel fichier d\'échange standard de compensation est historiquement utilisé dans le réseau Mastercard pour la télécollecte ?',
      options: ['Fichier IPM (Integrated Processing Module)', 'Fichier BASE II', 'Fichier SEPA XML', 'Fichier CSV Excel'],
      correctIndex: 0,
      explanation: 'Mastercard utilise le format IPM (Integrated Processing Module) pour l\'échange de fichiers de compensation et de règlement.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-150',
      category: 'Compensation & Normes',
      question: 'Quel format de fichier de compensation est historiquement utilisé dans le réseau Visa pour le clearing mondial ?',
      options: ['BASE II', 'IPM', 'SWIFT MT103', 'JSON REST'],
      correctIndex: 0,
      explanation: 'Visa utilise le système et le format de messagerie BASE II pour la compensation financière des transactions.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-151',
      category: 'Compensation & Normes',
      question: 'Qu\'est-ce qu\'une transaction \'On-Us\' dans le traitement d\'un switch de paiement bancaire ?',
      options: ['Une transaction où la carte appartient à la même banque que celle qui possède le terminal ou le GAB (pas d\'échange interbancaire externe)', 'Une transaction payée en monnaie étrangère', 'Une transaction suspecte signalée à la police', 'Un paiement sans contact'],
      correctIndex: 0,
      explanation: 'Une transaction On-Us est traitée en circuit fermé interne à la banque (l\'émetteur est identique à l\'acquéreur), évitant les frais de réseau externe.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-152',
      category: 'Compensation & Normes',
      question: 'Qu\'est-ce qu\'une transaction \'Off-Us\' ?',
      options: ['Une transaction qui passe par un réseau national ou international car l\'émetteur de la carte est différent de la banque acquéreuse', 'Une transaction refusée', 'Un paiement effectué hors-ligne', 'Une transaction sans ticket'],
      correctIndex: 0,
      explanation: 'Une transaction Off-Us nécessite l\'intervention d\'un switch d\'interconnexion pour router les flux entre deux banques distinctes.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-153',
      category: 'Compensation & Normes',
      question: 'Dans le cadre de la directive DSP2, qu\'est-ce que l\'exemption de Strong Customer Authentication basée sur l\'analyse des risques (TRA - Transaction Risk Analysis) ?',
      options: ['L\'exemption de code PIN pour les amis du commerçant', 'La possibilité d\'exempter une transaction e-commerce d\'authentification forte 3DS si le taux de fraude de la banque ou du PSP est inférieur aux seuils réglementaires', 'L\'absence totale de sécurité pour les montants pairs', 'Une dispense accordée aux entreprises publiques'],
      correctIndex: 1,
      explanation: 'L\'analyse des risques (TRA) permet aux acquéreurs ou émetteurs vertueux présentant un taux de fraude très faible d\'offrir un parcours d\'achat fluide (frictionless).',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-154',
      category: 'Compensation & Normes',
      question: 'Que signifie le sigle GIM-UEMOA dans l\'espace bancaire de l\'Afrique de l\'Ouest ?',
      options: ['Groupement Interbancaire Monétique de l\'Union Économique et Monétaire Ouest-Africaine', 'Gestion Informatique Monétaire de l\'Union Européenne', 'Groupe International Mastercard Ouest Africain', 'Guichet Interbancaire Mutualisé'],
      correctIndex: 0,
      explanation: 'Le GIM-UEMOA est le groupement monétique régional fédérant les établissements financiers de l\'UEMOA pour l\'interbancarité des retraits et paiements.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-155',
      category: 'Compensation & Normes',
      question: 'Quel est le rôle du protocole 3-D Secure (3DS 2.0 / EMV 3DS) dans les paiements sur Internet ?',
      options: ['Imprimer automatiquement les factures', 'Authentifier le porteur auprès de sa banque émettrice (via biométrie ou SMS) lors d\'un achat e-commerce afin de lutter contre la fraude et déplacer la responsabilité', 'Accélérer le téléchargement des pages web', 'Chiffrer le disque dur du serveur web'],
      correctIndex: 1,
      explanation: 'EMV 3DS authentifie l\'acheteur en temps réel avec transmission de données de contexte riches (appareil, géolocalisation, historique) à l\'émetteur.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-156',
      category: 'Compensation & Normes',
      question: 'Qu\'est-ce que la \'Pré-autorisation\' (Pre-auth) couramment employée dans l\'hôtellerie ou la location de véhicules ?',
      options: ['Un paiement en liquide', 'Une réservation temporaire de fonds bloquant un montant sur le compte du porteur sans débit immédiat, complétée ultérieurement par une capture financière (Completion)', 'Une remise commerciale', 'Un prêt bancaire à taux zéro'],
      correctIndex: 1,
      explanation: 'La pré-autorisation bloque les fonds (MTI 0100) pour garantir le paiement des prestations futures, finalisée par un MTI 0220/0200 lors du départ du client.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-157',
      category: 'Compensation & Normes',
      question: 'Quel est le rôle de la réconciliation monétique quotidienne (Reconciliation / Balancing) ?',
      options: ['Vérifier la concordance exacte entre les totaux enregistrés par les terminaux, les journaux du switch et les montants crédités par la compensation', 'Faire la paix entre les banques concurrentes', 'Nettoyer les disques durs des serveurs', 'Calculer le salaire des caissiers'],
      correctIndex: 0,
      explanation: 'La réconciliation détecte les écarts comptables, les suspens, les orphelines et les transactions non réglées entre les différents maillons de la chaîne.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-158',
      category: 'Compensation & Normes',
      question: 'Que signifie le sigle STIP (Stand-In Processing) chez un processeur de paiement ?',
      options: ['La délégation d\'autorisation au réseau ou switch pour approuver les transactions selon des règles prédéfinies lorsque le serveur de la banque émettrice est indisponible', 'L\'arrêt complet de tous les paiements', 'La saisie manuelle des transactions sur papier', 'Un test d\'intrusion annuel'],
      correctIndex: 0,
      explanation: 'Le STIP autorise le réseau (ex: Visa, switch national) à répondre à la place de l\'émetteur défaillant dans les limites de plafonds négociées pour garantir la continuité de service.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-159',
      category: 'Compensation & Normes',
      question: 'Dans le règlement brut en temps réel (RTGS), comment sont traitées les opérations interbancaires ?',
      options: ['Toutes les transactions sont regroupées et compensées une fois par mois', 'Chaque transaction est réglée individuellement, en continu et immédiatement dès sa réception sans compensation préalable', 'Les paiements sont traités par tirage au sort', 'Les transactions de moins de 100 000 euros sont ignorées'],
      correctIndex: 1,
      explanation: 'En RTGS (Real-Time Gross Settlement), les transferts sont individuels, continus, immédiats et ont un caractère définitif et irrévocable.',
      xpReward: 30,
    ),
    QuizQuestion(
      id: 'Q-160',
      category: 'Compensation & Normes',
      question: 'Quelle entité internationale publie les spécifications universelles de la carte à puce bancaire et du sans-contact EMV ?',
      options: ['L\'Organisation Mondiale du Commerce (OMC)', 'EMVCo (consortium détenu conjointement par American Express, Discover, JCB, Mastercard, UnionPay et Visa)', 'La Banque Centrale Européenne', 'L\'Union Internationale des Télécommunications'],
      correctIndex: 1,
      explanation: 'EMVCo est l\'organisme technique mondial de normalisation assurant l\'interopérabilité des puces, terminaux et solutions de paiement sécurisées.',
      xpReward: 30,
    ),
  ];

  static List<QuizQuestion> getQuestionsByCategory(String category) {
    if (category == 'TOUS') return allQuestions;
    return allQuestions.where((q) => q.category == category).toList();
  }
}
