export type ReferenceIncident = {
  reference: string;
  title: string;
  domain: string;
  component: string;
  analysisKeys: string;
  knowledgeStatus: "REFERENCE_SCENARIO" | "VALIDATED";
};

export const referenceIncidents: ReferenceIncident[] = [
  {
    reference: "INC-001",
    title: "GAB - Retraits en échec suite à timeout CBS / lock ACCOUNT",
    domain: "GAB",
    component: "CBS/DB",
    analysisKeys: "DE39, STAN, RRN",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-002",
    title: "GAB - DE39=91 massif avec timeout côté Issuer",
    domain: "GAB",
    component: "Issuer/DB",
    analysisKeys: "DE39=91, STAN, RRN",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-003",
    title: "GAB - Carte acceptée mais aucun cash délivré",
    domain: "GAB",
    component: "ATM/Host",
    analysisKeys: "0200/0210, DE39, DE11",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-004",
    title: "GAB - Compte débité mais cash non délivré",
    domain: "GAB",
    component: "CBS/Host",
    analysisKeys: "DE4, DE11, DE37, DE90",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-005",
    title: "GAB - Double débit après timeout transactionnel",
    domain: "GAB",
    component: "CBS/Reversal",
    analysisKeys: "DE11, DE37, DE90",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-006",
    title: "GAB - Reversal absent après transaction timeout",
    domain: "GAB",
    component: "Payway/Switch",
    analysisKeys: "0400/0410, DE90",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-007",
    title: "GAB - Reversal rejeté par l'Host",
    domain: "GAB",
    component: "Host",
    analysisKeys: "0400/0410, DE39",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-008",
    title: "GAB - STAN dupliqué",
    domain: "GAB",
    component: "Payway/Switch",
    analysisKeys: "DE11",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-009",
    title: "GAB - RRN dupliqué ou incohérent",
    domain: "GAB",
    component: "Payway/Switch",
    analysisKeys: "DE37",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-010",
    title: "GAB - Terminal ID inconnu ou mal routé",
    domain: "GAB",
    component: "Payway/Routing",
    analysisKeys: "DE41",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-011",
    title: "TPE - Paiements systématiquement rejetés",
    domain: "TPE",
    component: "Payway/Host",
    analysisKeys: "DE39, DE41",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-012",
    title: "TPE - DE39=05 sur un périmètre marchand",
    domain: "TPE",
    component: "Issuer",
    analysisKeys: "DE39=05",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-013",
    title: "TPE - DE39=91 sur un périmètre marchand",
    domain: "TPE",
    component: "Issuer/Switch",
    analysisKeys: "DE39=91",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-014",
    title: "TPE - Timeout entre Payway et Host",
    domain: "TPE",
    component: "Payway/Host",
    analysisKeys: "timeout, MTI",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-015",
    title: "TPE - Transaction autorisée mais non comptabilisée",
    domain: "TPE",
    component: "CBS/Clearing",
    analysisKeys: "DE38, DE39, DE90",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-016",
    title: "TPE - Reversal automatique non généré",
    domain: "TPE",
    component: "Payway",
    analysisKeys: "0400/0410",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-017",
    title: "TPE - Terminal non joignable",
    domain: "TPE",
    component: "Réseau/Terminal",
    analysisKeys: "DE41",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-018",
    title: "TPE - Mauvaise devise ou currency code",
    domain: "TPE",
    component: "Host/Mapping",
    analysisKeys: "DE49",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-019",
    title: "TPE - Montant incorrect dans DE4",
    domain: "TPE",
    component: "Mapping/Interface",
    analysisKeys: "DE4",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-020",
    title: "TPE - Merchant ID mal configuré",
    domain: "TPE",
    component: "Routing",
    analysisKeys: "DE42",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-021",
    title: "EMV - Transaction puce rejetée",
    domain: "Carte",
    component: "EMV/Host",
    analysisKeys: "DE55, DE39",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-022",
    title: "EMV - ARQC invalide",
    domain: "Carte",
    component: "HSM/Issuer",
    analysisKeys: "DE55",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-023",
    title: "EMV - Cryptogramme de transaction non validé",
    domain: "Carte",
    component: "HSM/Issuer",
    analysisKeys: "DE55",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-024",
    title: "PIN - PIN block invalide",
    domain: "Carte",
    component: "HSM",
    analysisKeys: "DE52, DE53",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-025",
    title: "PIN - Erreur de traduction de PIN block",
    domain: "Carte",
    component: "HSM/Switch",
    analysisKeys: "DE52",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-026",
    title: "HSM - HSM indisponible",
    domain: "Infrastructure",
    component: "HSM",
    analysisKeys: "DE53",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-027",
    title: "HSM - Latence excessive des requêtes cryptographiques",
    domain: "Infrastructure",
    component: "HSM",
    analysisKeys: "latence/HSM",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-028",
    title: "HSM - Clé cryptographique indisponible ou incorrecte",
    domain: "Infrastructure",
    component: "HSM",
    analysisKeys: "clé/crypto",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-029",
    title: "ISO 8583 - Bitmap incohérent",
    domain: "Interface",
    component: "ISO 8583",
    analysisKeys: "Bitmap",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-030",
    title: "ISO 8583 - Data Element obligatoire absent",
    domain: "Interface",
    component: "ISO 8583",
    analysisKeys: "DE",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-031",
    title: "ISO 8583 - Format ou longueur d'un DE incorrect",
    domain: "Interface",
    component: "ISO 8583",
    analysisKeys: "DE",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-032",
    title: "ISO 8583 - MTI inattendu ou non supporté",
    domain: "Interface",
    component: "ISO 8583",
    analysisKeys: "MTI",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-033",
    title: "Payway - Problème de routage vers un Host",
    domain: "Payway",
    component: "Routing",
    analysisKeys: "destination/Host",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-034",
    title: "Payway - Queue de messages en accumulation",
    domain: "Payway",
    component: "Payway/Messaging",
    analysisKeys: "queue",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-035",
    title: "Payway - Service d'interface arrêté",
    domain: "Payway",
    component: "Payway",
    analysisKeys: "service/status",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-036",
    title: "Payway - Pool de connexions saturé",
    domain: "Payway",
    component: "Payway/DB",
    analysisKeys: "connection pool",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-037",
    title: "Payway - Latence anormale d'un Host",
    domain: "Payway",
    component: "Host/Réseau",
    analysisKeys: "latence",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-038",
    title: "Payway - Réponse reçue mais non corrélée",
    domain: "Payway",
    component: "Payway/Switch",
    analysisKeys: "STAN/RRN",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-039",
    title: "Host - Réponse tardive après expiration du timeout",
    domain: "Host",
    component: "Host/Network",
    analysisKeys: "timeout",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-040",
    title: "Host - Host UP mais transactions rejetées massivement",
    domain: "Host",
    component: "Host/Issuer",
    analysisKeys: "DE39",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-041",
    title: "Issuer - Base ACCOUNT verrouillée",
    domain: "Issuer",
    component: "DB",
    analysisKeys: "locks/sessions",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-042",
    title: "Issuer - Pool de sessions DB saturé",
    domain: "Issuer",
    component: "DB",
    analysisKeys: "sessions",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-043",
    title: "Issuer - Requête ACCOUNT très lente",
    domain: "Issuer",
    component: "DB",
    analysisKeys: "SQL/performance",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-044",
    title: "Issuer - Session Back Office bloquante",
    domain: "Issuer",
    component: "DB/Back Office",
    analysisKeys: "lock",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-045",
    title: "Clearing - Fichier batch non généré",
    domain: "Clearing",
    component: "Batch",
    analysisKeys: "batch/file",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-046",
    title: "Clearing - Batch bloqué sur une étape",
    domain: "Clearing",
    component: "Batch/DB",
    analysisKeys: "batch/lock",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-047",
    title: "Clearing - Suspense comptable sur transactions VISA/MC",
    domain: "Clearing",
    component: "CBS/Reconciliation",
    analysisKeys: "DE4/DE39/DE90",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-048",
    title: "Clearing - Écart entre transactions et fichier de compensation",
    domain: "Clearing",
    component: "Reconciliation",
    analysisKeys: "STAN/RRN",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-049",
    title: "Network Management - Echo test 0800/0810 en échec",
    domain: "Réseau",
    component: "Network Management",
    analysisKeys: "MTI 0800/0810, DE70",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-050",
    title: "Production - Déploiement monétique avec régression de transactions",
    domain: "Production",
    component: "Release/Payway",
    analysisKeys: "MTI/DE39/logs",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-051",
    title: "GAB - EPP Clavier - Anomalie type 1 sur PIN Pad chiffrant",
    domain: "GAB",
    component: "ATM/EPP",
    analysisKeys: "DE52, KSN, DUKPT",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-052",
    title: "GAB - Lecteur Carte - Anomalie type 1 sur Lecteur hybride motorisé",
    domain: "GAB",
    component: "ATM/Lecteur",
    analysisKeys: "Track2, Chip, MTI 0200",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-053",
    title: "GAB - Cassette Billets - Anomalie type 1 sur Module de distribution",
    domain: "GAB",
    component: "ATM/Cassettes",
    analysisKeys: "Cassette Status, DE4",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-054",
    title: "GAB - Dépôt Automatique - Anomalie type 1 sur Module de recyclage/dépôt",
    domain: "GAB",
    component: "ATM/Dépôt",
    analysisKeys: "Envelope, Depository, 0200",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-055",
    title: "GAB - Audit Trail - Anomalie type 1 sur Journal électronique",
    domain: "GAB",
    component: "ATM/Journal",
    analysisKeys: "EJ, Decryption, Audit",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-056",
    title: "TPE - Paiement NFC - Anomalie type 1 sur Lecteur NFC sans contact",
    domain: "TPE",
    component: "TPE/Contactless",
    analysisKeys: "NFC, Tag 9F6E, DE55",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-057",
    title: "TPE - Passerelle Monétique - Anomalie type 1 sur Concentrateur TPE",
    domain: "TPE",
    component: "TPE/Passerelle",
    analysisKeys: "TLS, IP, Port 8443",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-058",
    title: "TPE - Télécollecte Fin Journée - Anomalie type 1 sur Télécollecte CB",
    domain: "TPE",
    component: "TPE/Télécollecte",
    analysisKeys: "MTI 0500, Batch Upload",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-059",
    title: "TPE - Conversion Devise DCC - Anomalie type 1 sur DCC Dynamic Currency",
    domain: "TPE",
    component: "TPE/Multi-devise",
    analysisKeys: "DE49, DE51, DE6",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-060",
    title: "TPE - Remboursement Commerçant - Anomalie type 1 sur Opération Refund",
    domain: "TPE",
    component: "TPE/Remboursement",
    analysisKeys: "MTI 0200, DE3=200000",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-061",
    title: "Carte - Kernel EMV Contact - Anomalie type 1 sur Noyau EMV L2",
    domain: "Carte",
    component: "EMV/Kernel",
    analysisKeys: "Tag 9F36, Tag 9F10, DE55",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-062",
    title: "Carte - Authentification 3DSv2 - Anomalie type 1 sur Plateforme 3D-Secure",
    domain: "Carte",
    component: "Carte/3DS",
    analysisKeys: "CAVV, AAV, E-commerce",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-063",
    title: "Carte - Token ApplePay/GooglePay - Anomalie type 1 sur Service de Tokenisation",
    domain: "Carte",
    component: "Carte/Tokenisation",
    analysisKeys: "PAR, DPAN, Token Vault",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-064",
    title: "Carte - Dépassement Plafond - Anomalie type 1 sur Gestion des plafonds cartes",
    domain: "Carte",
    component: "Carte/Plafond",
    analysisKeys: "DE39=61, DE39=65",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-065",
    title: "Infrastructure - Sécurité Clé LMK - Anomalie type 1 sur Local Master Key",
    domain: "Infrastructure",
    component: "HSM/LMK",
    analysisKeys: "LMK, HSM PayShield",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-066",
    title: "Infrastructure - Validation CVV2 - Anomalie type 1 sur Générateur CVV/iCVV",
    domain: "Infrastructure",
    component: "HSM/CVV",
    analysisKeys: "CVV2, CSC, DE39=82",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-067",
    title: "Infrastructure - Vérification PVV/IBM3624 - Anomalie type 1 sur PIN Verification Value",
    domain: "Infrastructure",
    component: "HSM/PVV",
    analysisKeys: "PVV, PVKI, DE52",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-068",
    title: "Infrastructure - Certificat Root CA EMV - Anomalie type 1 sur Infrastructure PKI",
    domain: "Infrastructure",
    component: "HSM/Certificats",
    analysisKeys: "EMV CA Public Key, RID",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-069",
    title: "Interface - Décodage Processing Code - Anomalie type 1 sur Processing Code",
    domain: "Interface",
    component: "ISO 8583/DE3",
    analysisKeys: "DE3 (000000, 010000, 310000)",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-070",
    title: "Interface - Identification Marchand - Anomalie type 1 sur Card Acceptor Name",
    domain: "Interface",
    component: "ISO 8583/DE43",
    analysisKeys: "DE43 City/Country",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-071",
    title: "Interface - Montants Additionnels Solde - Anomalie type 1 sur Additional Amounts",
    domain: "Interface",
    component: "ISO 8583/DE54",
    analysisKeys: "DE54 Available Balance",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-072",
    title: "Interface - Données Privées Terminal - Anomalie type 1 sur Terminal Data",
    domain: "Interface",
    component: "ISO 8583/DE60",
    analysisKeys: "DE60 Terminal Capability",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-073",
    title: "Switch - Interface VISA SMS - Anomalie type 1 sur Lien Direct VISA Base I/II",
    domain: "Switch",
    component: "Switch/VISA",
    analysisKeys: "VISA VIP, VAP, 0100",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-074",
    title: "Switch - Interface Mastercard Banknet - Anomalie type 1 sur Lien Mastercard MIP",
    domain: "Switch",
    component: "Switch/Mastercard",
    analysisKeys: "MIP, 0100, DE48 SE",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-075",
    title: "Switch - Interbancarité GIMAC - Anomalie type 1 sur Switch Régional GIMAC",
    domain: "Switch",
    component: "Switch/GIMAC",
    analysisKeys: "GIMAC MTI, 0200, DE100",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-076",
    title: "Switch - Bascule Haute Disponibilité - Anomalie type 1 sur Routage Fallback",
    domain: "Switch",
    component: "Switch/Bascule",
    analysisKeys: "Active/Passive Switch, VIP",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-077",
    title: "Clearing - Extourne Comptable - Anomalie type 1 sur Contrepassation d'écritures",
    domain: "Clearing",
    component: "CBS/Contrepassation",
    analysisKeys: "DE90, Annulation CBS",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-078",
    title: "Clearing - Heure de Coupure Cut-Off - Anomalie type 1 sur Arrêté comptable journalier",
    domain: "Clearing",
    component: "Clearing/CutOff",
    analysisKeys: "Cut-Off, Batch Balance",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-079",
    title: "Clearing - Rejet Lot Compensation - Anomalie type 1 sur Rejet fichier compensation",
    domain: "Clearing",
    component: "Clearing/Rejet",
    analysisKeys: "Fichier EPA, Chargeback",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-080",
    title: "Clearing - Litige & Chargeback TC40 - Anomalie type 1 sur Déclaration Impayés/Fraude",
    domain: "Clearing",
    component: "Clearing/Fraude",
    analysisKeys: "Chargeback, Representment",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-081",
    title: "GAB - EPP Clavier - Anomalie type 2 sur PIN Pad chiffrant",
    domain: "GAB",
    component: "ATM/EPP",
    analysisKeys: "DE52, KSN, DUKPT",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-082",
    title: "GAB - Lecteur Carte - Anomalie type 2 sur Lecteur hybride motorisé",
    domain: "GAB",
    component: "ATM/Lecteur",
    analysisKeys: "Track2, Chip, MTI 0200",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-083",
    title: "GAB - Cassette Billets - Anomalie type 2 sur Module de distribution",
    domain: "GAB",
    component: "ATM/Cassettes",
    analysisKeys: "Cassette Status, DE4",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-084",
    title: "GAB - Dépôt Automatique - Anomalie type 2 sur Module de recyclage/dépôt",
    domain: "GAB",
    component: "ATM/Dépôt",
    analysisKeys: "Envelope, Depository, 0200",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-085",
    title: "GAB - Audit Trail - Anomalie type 2 sur Journal électronique",
    domain: "GAB",
    component: "ATM/Journal",
    analysisKeys: "EJ, Decryption, Audit",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-086",
    title: "TPE - Paiement NFC - Anomalie type 2 sur Lecteur NFC sans contact",
    domain: "TPE",
    component: "TPE/Contactless",
    analysisKeys: "NFC, Tag 9F6E, DE55",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-087",
    title: "TPE - Passerelle Monétique - Anomalie type 2 sur Concentrateur TPE",
    domain: "TPE",
    component: "TPE/Passerelle",
    analysisKeys: "TLS, IP, Port 8443",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-088",
    title: "TPE - Télécollecte Fin Journée - Anomalie type 2 sur Télécollecte CB",
    domain: "TPE",
    component: "TPE/Télécollecte",
    analysisKeys: "MTI 0500, Batch Upload",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-089",
    title: "TPE - Conversion Devise DCC - Anomalie type 2 sur DCC Dynamic Currency",
    domain: "TPE",
    component: "TPE/Multi-devise",
    analysisKeys: "DE49, DE51, DE6",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-090",
    title: "TPE - Remboursement Commerçant - Anomalie type 2 sur Opération Refund",
    domain: "TPE",
    component: "TPE/Remboursement",
    analysisKeys: "MTI 0200, DE3=200000",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-091",
    title: "Carte - Kernel EMV Contact - Anomalie type 2 sur Noyau EMV L2",
    domain: "Carte",
    component: "EMV/Kernel",
    analysisKeys: "Tag 9F36, Tag 9F10, DE55",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-092",
    title: "Carte - Authentification 3DSv2 - Anomalie type 2 sur Plateforme 3D-Secure",
    domain: "Carte",
    component: "Carte/3DS",
    analysisKeys: "CAVV, AAV, E-commerce",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-093",
    title: "Carte - Token ApplePay/GooglePay - Anomalie type 2 sur Service de Tokenisation",
    domain: "Carte",
    component: "Carte/Tokenisation",
    analysisKeys: "PAR, DPAN, Token Vault",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-094",
    title: "Carte - Dépassement Plafond - Anomalie type 2 sur Gestion des plafonds cartes",
    domain: "Carte",
    component: "Carte/Plafond",
    analysisKeys: "DE39=61, DE39=65",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-095",
    title: "Infrastructure - Sécurité Clé LMK - Anomalie type 2 sur Local Master Key",
    domain: "Infrastructure",
    component: "HSM/LMK",
    analysisKeys: "LMK, HSM PayShield",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-096",
    title: "Infrastructure - Validation CVV2 - Anomalie type 2 sur Générateur CVV/iCVV",
    domain: "Infrastructure",
    component: "HSM/CVV",
    analysisKeys: "CVV2, CSC, DE39=82",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-097",
    title: "Infrastructure - Vérification PVV/IBM3624 - Anomalie type 2 sur PIN Verification Value",
    domain: "Infrastructure",
    component: "HSM/PVV",
    analysisKeys: "PVV, PVKI, DE52",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-098",
    title: "Infrastructure - Certificat Root CA EMV - Anomalie type 2 sur Infrastructure PKI",
    domain: "Infrastructure",
    component: "HSM/Certificats",
    analysisKeys: "EMV CA Public Key, RID",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-099",
    title: "Interface - Décodage Processing Code - Anomalie type 2 sur Processing Code",
    domain: "Interface",
    component: "ISO 8583/DE3",
    analysisKeys: "DE3 (000000, 010000, 310000)",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-100",
    title: "Interface - Identification Marchand - Anomalie type 2 sur Card Acceptor Name",
    domain: "Interface",
    component: "ISO 8583/DE43",
    analysisKeys: "DE43 City/Country",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-101",
    title: "Interface - Montants Additionnels Solde - Anomalie type 2 sur Additional Amounts",
    domain: "Interface",
    component: "ISO 8583/DE54",
    analysisKeys: "DE54 Available Balance",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-102",
    title: "Interface - Données Privées Terminal - Anomalie type 2 sur Terminal Data",
    domain: "Interface",
    component: "ISO 8583/DE60",
    analysisKeys: "DE60 Terminal Capability",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-103",
    title: "Switch - Interface VISA SMS - Anomalie type 2 sur Lien Direct VISA Base I/II",
    domain: "Switch",
    component: "Switch/VISA",
    analysisKeys: "VISA VIP, VAP, 0100",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-104",
    title: "Switch - Interface Mastercard Banknet - Anomalie type 2 sur Lien Mastercard MIP",
    domain: "Switch",
    component: "Switch/Mastercard",
    analysisKeys: "MIP, 0100, DE48 SE",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-105",
    title: "Switch - Interbancarité GIMAC - Anomalie type 2 sur Switch Régional GIMAC",
    domain: "Switch",
    component: "Switch/GIMAC",
    analysisKeys: "GIMAC MTI, 0200, DE100",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-106",
    title: "Switch - Bascule Haute Disponibilité - Anomalie type 2 sur Routage Fallback",
    domain: "Switch",
    component: "Switch/Bascule",
    analysisKeys: "Active/Passive Switch, VIP",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-107",
    title: "Clearing - Extourne Comptable - Anomalie type 2 sur Contrepassation d'écritures",
    domain: "Clearing",
    component: "CBS/Contrepassation",
    analysisKeys: "DE90, Annulation CBS",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-108",
    title: "Clearing - Heure de Coupure Cut-Off - Anomalie type 2 sur Arrêté comptable journalier",
    domain: "Clearing",
    component: "Clearing/CutOff",
    analysisKeys: "Cut-Off, Batch Balance",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-109",
    title: "Clearing - Rejet Lot Compensation - Anomalie type 2 sur Rejet fichier compensation",
    domain: "Clearing",
    component: "Clearing/Rejet",
    analysisKeys: "Fichier EPA, Chargeback",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-110",
    title: "Clearing - Litige & Chargeback TC40 - Anomalie type 2 sur Déclaration Impayés/Fraude",
    domain: "Clearing",
    component: "Clearing/Fraude",
    analysisKeys: "Chargeback, Representment",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-111",
    title: "GAB - EPP Clavier - Anomalie type 3 sur PIN Pad chiffrant",
    domain: "GAB",
    component: "ATM/EPP",
    analysisKeys: "DE52, KSN, DUKPT",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-112",
    title: "GAB - Lecteur Carte - Anomalie type 3 sur Lecteur hybride motorisé",
    domain: "GAB",
    component: "ATM/Lecteur",
    analysisKeys: "Track2, Chip, MTI 0200",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-113",
    title: "GAB - Cassette Billets - Anomalie type 3 sur Module de distribution",
    domain: "GAB",
    component: "ATM/Cassettes",
    analysisKeys: "Cassette Status, DE4",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-114",
    title: "GAB - Dépôt Automatique - Anomalie type 3 sur Module de recyclage/dépôt",
    domain: "GAB",
    component: "ATM/Dépôt",
    analysisKeys: "Envelope, Depository, 0200",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-115",
    title: "GAB - Audit Trail - Anomalie type 3 sur Journal électronique",
    domain: "GAB",
    component: "ATM/Journal",
    analysisKeys: "EJ, Decryption, Audit",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-116",
    title: "TPE - Paiement NFC - Anomalie type 3 sur Lecteur NFC sans contact",
    domain: "TPE",
    component: "TPE/Contactless",
    analysisKeys: "NFC, Tag 9F6E, DE55",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-117",
    title: "TPE - Passerelle Monétique - Anomalie type 3 sur Concentrateur TPE",
    domain: "TPE",
    component: "TPE/Passerelle",
    analysisKeys: "TLS, IP, Port 8443",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-118",
    title: "TPE - Télécollecte Fin Journée - Anomalie type 3 sur Télécollecte CB",
    domain: "TPE",
    component: "TPE/Télécollecte",
    analysisKeys: "MTI 0500, Batch Upload",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-119",
    title: "TPE - Conversion Devise DCC - Anomalie type 3 sur DCC Dynamic Currency",
    domain: "TPE",
    component: "TPE/Multi-devise",
    analysisKeys: "DE49, DE51, DE6",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-120",
    title: "TPE - Remboursement Commerçant - Anomalie type 3 sur Opération Refund",
    domain: "TPE",
    component: "TPE/Remboursement",
    analysisKeys: "MTI 0200, DE3=200000",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-121",
    title: "Carte - Kernel EMV Contact - Anomalie type 3 sur Noyau EMV L2",
    domain: "Carte",
    component: "EMV/Kernel",
    analysisKeys: "Tag 9F36, Tag 9F10, DE55",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-122",
    title: "Carte - Authentification 3DSv2 - Anomalie type 3 sur Plateforme 3D-Secure",
    domain: "Carte",
    component: "Carte/3DS",
    analysisKeys: "CAVV, AAV, E-commerce",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-123",
    title: "Carte - Token ApplePay/GooglePay - Anomalie type 3 sur Service de Tokenisation",
    domain: "Carte",
    component: "Carte/Tokenisation",
    analysisKeys: "PAR, DPAN, Token Vault",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-124",
    title: "Carte - Dépassement Plafond - Anomalie type 3 sur Gestion des plafonds cartes",
    domain: "Carte",
    component: "Carte/Plafond",
    analysisKeys: "DE39=61, DE39=65",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-125",
    title: "Infrastructure - Sécurité Clé LMK - Anomalie type 3 sur Local Master Key",
    domain: "Infrastructure",
    component: "HSM/LMK",
    analysisKeys: "LMK, HSM PayShield",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-126",
    title: "Infrastructure - Validation CVV2 - Anomalie type 3 sur Générateur CVV/iCVV",
    domain: "Infrastructure",
    component: "HSM/CVV",
    analysisKeys: "CVV2, CSC, DE39=82",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-127",
    title: "Infrastructure - Vérification PVV/IBM3624 - Anomalie type 3 sur PIN Verification Value",
    domain: "Infrastructure",
    component: "HSM/PVV",
    analysisKeys: "PVV, PVKI, DE52",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-128",
    title: "Infrastructure - Certificat Root CA EMV - Anomalie type 3 sur Infrastructure PKI",
    domain: "Infrastructure",
    component: "HSM/Certificats",
    analysisKeys: "EMV CA Public Key, RID",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-129",
    title: "Interface - Décodage Processing Code - Anomalie type 3 sur Processing Code",
    domain: "Interface",
    component: "ISO 8583/DE3",
    analysisKeys: "DE3 (000000, 010000, 310000)",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-130",
    title: "Interface - Identification Marchand - Anomalie type 3 sur Card Acceptor Name",
    domain: "Interface",
    component: "ISO 8583/DE43",
    analysisKeys: "DE43 City/Country",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-131",
    title: "Interface - Montants Additionnels Solde - Anomalie type 3 sur Additional Amounts",
    domain: "Interface",
    component: "ISO 8583/DE54",
    analysisKeys: "DE54 Available Balance",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-132",
    title: "Interface - Données Privées Terminal - Anomalie type 3 sur Terminal Data",
    domain: "Interface",
    component: "ISO 8583/DE60",
    analysisKeys: "DE60 Terminal Capability",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-133",
    title: "Switch - Interface VISA SMS - Anomalie type 3 sur Lien Direct VISA Base I/II",
    domain: "Switch",
    component: "Switch/VISA",
    analysisKeys: "VISA VIP, VAP, 0100",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-134",
    title: "Switch - Interface Mastercard Banknet - Anomalie type 3 sur Lien Mastercard MIP",
    domain: "Switch",
    component: "Switch/Mastercard",
    analysisKeys: "MIP, 0100, DE48 SE",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-135",
    title: "Switch - Interbancarité GIMAC - Anomalie type 3 sur Switch Régional GIMAC",
    domain: "Switch",
    component: "Switch/GIMAC",
    analysisKeys: "GIMAC MTI, 0200, DE100",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-136",
    title: "Switch - Bascule Haute Disponibilité - Anomalie type 3 sur Routage Fallback",
    domain: "Switch",
    component: "Switch/Bascule",
    analysisKeys: "Active/Passive Switch, VIP",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-137",
    title: "Clearing - Extourne Comptable - Anomalie type 3 sur Contrepassation d'écritures",
    domain: "Clearing",
    component: "CBS/Contrepassation",
    analysisKeys: "DE90, Annulation CBS",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-138",
    title: "Clearing - Heure de Coupure Cut-Off - Anomalie type 3 sur Arrêté comptable journalier",
    domain: "Clearing",
    component: "Clearing/CutOff",
    analysisKeys: "Cut-Off, Batch Balance",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-139",
    title: "Clearing - Rejet Lot Compensation - Anomalie type 3 sur Rejet fichier compensation",
    domain: "Clearing",
    component: "Clearing/Rejet",
    analysisKeys: "Fichier EPA, Chargeback",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-140",
    title: "Clearing - Litige & Chargeback TC40 - Anomalie type 3 sur Déclaration Impayés/Fraude",
    domain: "Clearing",
    component: "Clearing/Fraude",
    analysisKeys: "Chargeback, Representment",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-141",
    title: "GAB - EPP Clavier - Anomalie type 4 sur PIN Pad chiffrant",
    domain: "GAB",
    component: "ATM/EPP",
    analysisKeys: "DE52, KSN, DUKPT",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-142",
    title: "GAB - Lecteur Carte - Anomalie type 4 sur Lecteur hybride motorisé",
    domain: "GAB",
    component: "ATM/Lecteur",
    analysisKeys: "Track2, Chip, MTI 0200",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-143",
    title: "GAB - Cassette Billets - Anomalie type 4 sur Module de distribution",
    domain: "GAB",
    component: "ATM/Cassettes",
    analysisKeys: "Cassette Status, DE4",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-144",
    title: "GAB - Dépôt Automatique - Anomalie type 4 sur Module de recyclage/dépôt",
    domain: "GAB",
    component: "ATM/Dépôt",
    analysisKeys: "Envelope, Depository, 0200",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-145",
    title: "GAB - Audit Trail - Anomalie type 4 sur Journal électronique",
    domain: "GAB",
    component: "ATM/Journal",
    analysisKeys: "EJ, Decryption, Audit",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-146",
    title: "TPE - Paiement NFC - Anomalie type 4 sur Lecteur NFC sans contact",
    domain: "TPE",
    component: "TPE/Contactless",
    analysisKeys: "NFC, Tag 9F6E, DE55",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-147",
    title: "TPE - Passerelle Monétique - Anomalie type 4 sur Concentrateur TPE",
    domain: "TPE",
    component: "TPE/Passerelle",
    analysisKeys: "TLS, IP, Port 8443",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-148",
    title: "TPE - Télécollecte Fin Journée - Anomalie type 4 sur Télécollecte CB",
    domain: "TPE",
    component: "TPE/Télécollecte",
    analysisKeys: "MTI 0500, Batch Upload",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-149",
    title: "TPE - Conversion Devise DCC - Anomalie type 4 sur DCC Dynamic Currency",
    domain: "TPE",
    component: "TPE/Multi-devise",
    analysisKeys: "DE49, DE51, DE6",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-150",
    title: "TPE - Remboursement Commerçant - Anomalie type 4 sur Opération Refund",
    domain: "TPE",
    component: "TPE/Remboursement",
    analysisKeys: "MTI 0200, DE3=200000",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-151",
    title: "Carte - Kernel EMV Contact - Anomalie type 4 sur Noyau EMV L2",
    domain: "Carte",
    component: "EMV/Kernel",
    analysisKeys: "Tag 9F36, Tag 9F10, DE55",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-152",
    title: "Carte - Authentification 3DSv2 - Anomalie type 4 sur Plateforme 3D-Secure",
    domain: "Carte",
    component: "Carte/3DS",
    analysisKeys: "CAVV, AAV, E-commerce",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-153",
    title: "Carte - Token ApplePay/GooglePay - Anomalie type 4 sur Service de Tokenisation",
    domain: "Carte",
    component: "Carte/Tokenisation",
    analysisKeys: "PAR, DPAN, Token Vault",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-154",
    title: "Carte - Dépassement Plafond - Anomalie type 4 sur Gestion des plafonds cartes",
    domain: "Carte",
    component: "Carte/Plafond",
    analysisKeys: "DE39=61, DE39=65",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-155",
    title: "Infrastructure - Sécurité Clé LMK - Anomalie type 4 sur Local Master Key",
    domain: "Infrastructure",
    component: "HSM/LMK",
    analysisKeys: "LMK, HSM PayShield",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-156",
    title: "Infrastructure - Validation CVV2 - Anomalie type 4 sur Générateur CVV/iCVV",
    domain: "Infrastructure",
    component: "HSM/CVV",
    analysisKeys: "CVV2, CSC, DE39=82",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-157",
    title: "Infrastructure - Vérification PVV/IBM3624 - Anomalie type 4 sur PIN Verification Value",
    domain: "Infrastructure",
    component: "HSM/PVV",
    analysisKeys: "PVV, PVKI, DE52",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-158",
    title: "Infrastructure - Certificat Root CA EMV - Anomalie type 4 sur Infrastructure PKI",
    domain: "Infrastructure",
    component: "HSM/Certificats",
    analysisKeys: "EMV CA Public Key, RID",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-159",
    title: "Interface - Décodage Processing Code - Anomalie type 4 sur Processing Code",
    domain: "Interface",
    component: "ISO 8583/DE3",
    analysisKeys: "DE3 (000000, 010000, 310000)",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-160",
    title: "Interface - Identification Marchand - Anomalie type 4 sur Card Acceptor Name",
    domain: "Interface",
    component: "ISO 8583/DE43",
    analysisKeys: "DE43 City/Country",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-161",
    title: "Interface - Montants Additionnels Solde - Anomalie type 4 sur Additional Amounts",
    domain: "Interface",
    component: "ISO 8583/DE54",
    analysisKeys: "DE54 Available Balance",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-162",
    title: "Interface - Données Privées Terminal - Anomalie type 4 sur Terminal Data",
    domain: "Interface",
    component: "ISO 8583/DE60",
    analysisKeys: "DE60 Terminal Capability",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-163",
    title: "Switch - Interface VISA SMS - Anomalie type 4 sur Lien Direct VISA Base I/II",
    domain: "Switch",
    component: "Switch/VISA",
    analysisKeys: "VISA VIP, VAP, 0100",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-164",
    title: "Switch - Interface Mastercard Banknet - Anomalie type 4 sur Lien Mastercard MIP",
    domain: "Switch",
    component: "Switch/Mastercard",
    analysisKeys: "MIP, 0100, DE48 SE",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-165",
    title: "Switch - Interbancarité GIMAC - Anomalie type 4 sur Switch Régional GIMAC",
    domain: "Switch",
    component: "Switch/GIMAC",
    analysisKeys: "GIMAC MTI, 0200, DE100",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-166",
    title: "Switch - Bascule Haute Disponibilité - Anomalie type 4 sur Routage Fallback",
    domain: "Switch",
    component: "Switch/Bascule",
    analysisKeys: "Active/Passive Switch, VIP",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-167",
    title: "Clearing - Extourne Comptable - Anomalie type 4 sur Contrepassation d'écritures",
    domain: "Clearing",
    component: "CBS/Contrepassation",
    analysisKeys: "DE90, Annulation CBS",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-168",
    title: "Clearing - Heure de Coupure Cut-Off - Anomalie type 4 sur Arrêté comptable journalier",
    domain: "Clearing",
    component: "Clearing/CutOff",
    analysisKeys: "Cut-Off, Batch Balance",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-169",
    title: "Clearing - Rejet Lot Compensation - Anomalie type 4 sur Rejet fichier compensation",
    domain: "Clearing",
    component: "Clearing/Rejet",
    analysisKeys: "Fichier EPA, Chargeback",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-170",
    title: "Clearing - Litige & Chargeback TC40 - Anomalie type 4 sur Déclaration Impayés/Fraude",
    domain: "Clearing",
    component: "Clearing/Fraude",
    analysisKeys: "Chargeback, Representment",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-171",
    title: "GAB - EPP Clavier - Anomalie type 5 sur PIN Pad chiffrant",
    domain: "GAB",
    component: "ATM/EPP",
    analysisKeys: "DE52, KSN, DUKPT",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-172",
    title: "GAB - Lecteur Carte - Anomalie type 5 sur Lecteur hybride motorisé",
    domain: "GAB",
    component: "ATM/Lecteur",
    analysisKeys: "Track2, Chip, MTI 0200",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-173",
    title: "GAB - Cassette Billets - Anomalie type 5 sur Module de distribution",
    domain: "GAB",
    component: "ATM/Cassettes",
    analysisKeys: "Cassette Status, DE4",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-174",
    title: "GAB - Dépôt Automatique - Anomalie type 5 sur Module de recyclage/dépôt",
    domain: "GAB",
    component: "ATM/Dépôt",
    analysisKeys: "Envelope, Depository, 0200",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-175",
    title: "GAB - Audit Trail - Anomalie type 5 sur Journal électronique",
    domain: "GAB",
    component: "ATM/Journal",
    analysisKeys: "EJ, Decryption, Audit",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-176",
    title: "TPE - Paiement NFC - Anomalie type 5 sur Lecteur NFC sans contact",
    domain: "TPE",
    component: "TPE/Contactless",
    analysisKeys: "NFC, Tag 9F6E, DE55",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-177",
    title: "TPE - Passerelle Monétique - Anomalie type 5 sur Concentrateur TPE",
    domain: "TPE",
    component: "TPE/Passerelle",
    analysisKeys: "TLS, IP, Port 8443",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-178",
    title: "TPE - Télécollecte Fin Journée - Anomalie type 5 sur Télécollecte CB",
    domain: "TPE",
    component: "TPE/Télécollecte",
    analysisKeys: "MTI 0500, Batch Upload",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-179",
    title: "TPE - Conversion Devise DCC - Anomalie type 5 sur DCC Dynamic Currency",
    domain: "TPE",
    component: "TPE/Multi-devise",
    analysisKeys: "DE49, DE51, DE6",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-180",
    title: "TPE - Remboursement Commerçant - Anomalie type 5 sur Opération Refund",
    domain: "TPE",
    component: "TPE/Remboursement",
    analysisKeys: "MTI 0200, DE3=200000",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-181",
    title: "Carte - Kernel EMV Contact - Anomalie type 5 sur Noyau EMV L2",
    domain: "Carte",
    component: "EMV/Kernel",
    analysisKeys: "Tag 9F36, Tag 9F10, DE55",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-182",
    title: "Carte - Authentification 3DSv2 - Anomalie type 5 sur Plateforme 3D-Secure",
    domain: "Carte",
    component: "Carte/3DS",
    analysisKeys: "CAVV, AAV, E-commerce",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-183",
    title: "Carte - Token ApplePay/GooglePay - Anomalie type 5 sur Service de Tokenisation",
    domain: "Carte",
    component: "Carte/Tokenisation",
    analysisKeys: "PAR, DPAN, Token Vault",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-184",
    title: "Carte - Dépassement Plafond - Anomalie type 5 sur Gestion des plafonds cartes",
    domain: "Carte",
    component: "Carte/Plafond",
    analysisKeys: "DE39=61, DE39=65",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-185",
    title: "Infrastructure - Sécurité Clé LMK - Anomalie type 5 sur Local Master Key",
    domain: "Infrastructure",
    component: "HSM/LMK",
    analysisKeys: "LMK, HSM PayShield",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-186",
    title: "Infrastructure - Validation CVV2 - Anomalie type 5 sur Générateur CVV/iCVV",
    domain: "Infrastructure",
    component: "HSM/CVV",
    analysisKeys: "CVV2, CSC, DE39=82",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-187",
    title: "Infrastructure - Vérification PVV/IBM3624 - Anomalie type 5 sur PIN Verification Value",
    domain: "Infrastructure",
    component: "HSM/PVV",
    analysisKeys: "PVV, PVKI, DE52",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-188",
    title: "Infrastructure - Certificat Root CA EMV - Anomalie type 5 sur Infrastructure PKI",
    domain: "Infrastructure",
    component: "HSM/Certificats",
    analysisKeys: "EMV CA Public Key, RID",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-189",
    title: "Interface - Décodage Processing Code - Anomalie type 5 sur Processing Code",
    domain: "Interface",
    component: "ISO 8583/DE3",
    analysisKeys: "DE3 (000000, 010000, 310000)",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-190",
    title: "Interface - Identification Marchand - Anomalie type 5 sur Card Acceptor Name",
    domain: "Interface",
    component: "ISO 8583/DE43",
    analysisKeys: "DE43 City/Country",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-191",
    title: "Interface - Montants Additionnels Solde - Anomalie type 5 sur Additional Amounts",
    domain: "Interface",
    component: "ISO 8583/DE54",
    analysisKeys: "DE54 Available Balance",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-192",
    title: "Interface - Données Privées Terminal - Anomalie type 5 sur Terminal Data",
    domain: "Interface",
    component: "ISO 8583/DE60",
    analysisKeys: "DE60 Terminal Capability",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-193",
    title: "Switch - Interface VISA SMS - Anomalie type 5 sur Lien Direct VISA Base I/II",
    domain: "Switch",
    component: "Switch/VISA",
    analysisKeys: "VISA VIP, VAP, 0100",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-194",
    title: "Switch - Interface Mastercard Banknet - Anomalie type 5 sur Lien Mastercard MIP",
    domain: "Switch",
    component: "Switch/Mastercard",
    analysisKeys: "MIP, 0100, DE48 SE",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-195",
    title: "Switch - Interbancarité GIMAC - Anomalie type 5 sur Switch Régional GIMAC",
    domain: "Switch",
    component: "Switch/GIMAC",
    analysisKeys: "GIMAC MTI, 0200, DE100",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-196",
    title: "Switch - Bascule Haute Disponibilité - Anomalie type 5 sur Routage Fallback",
    domain: "Switch",
    component: "Switch/Bascule",
    analysisKeys: "Active/Passive Switch, VIP",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-197",
    title: "Clearing - Extourne Comptable - Anomalie type 5 sur Contrepassation d'écritures",
    domain: "Clearing",
    component: "CBS/Contrepassation",
    analysisKeys: "DE90, Annulation CBS",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-198",
    title: "Clearing - Heure de Coupure Cut-Off - Anomalie type 5 sur Arrêté comptable journalier",
    domain: "Clearing",
    component: "Clearing/CutOff",
    analysisKeys: "Cut-Off, Batch Balance",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-199",
    title: "Clearing - Rejet Lot Compensation - Anomalie type 5 sur Rejet fichier compensation",
    domain: "Clearing",
    component: "Clearing/Rejet",
    analysisKeys: "Fichier EPA, Chargeback",
    knowledgeStatus: "VALIDATED" as const,
  },
  {
    reference: "INC-200",
    title: "Clearing - Litige & Chargeback TC40 - Anomalie type 5 sur Déclaration Impayés/Fraude",
    domain: "Clearing",
    component: "Clearing/Fraude",
    analysisKeys: "Chargeback, Representment",
    knowledgeStatus: "VALIDATED" as const,
  }
];
